const DICTIONARY = {
    es: {
        titulo_app: "SIPVEC - Sistema de Inteligencia Comercial",
        bienvenida: "BIENVENIDOS",
        menu_quienes: "QUIÉNES SOMOS",
        menu_excelencia: "EXCELENCIA",
        menu_asistente: "ASISTENTE RAPIDO Y DUDAS",
        menu_redes: "WHATSAPP Y REDES SOCIALES",
        btn_evolucion: "VIDEOS / VIVE CON NOSOTROS LA EVOLUCION",
        btn_asesor: "¡ELIGE A TU ASESOR ESPECIALIZADO / MAPS!",
        btn_cuestionario: "Iniciar Cuestionario",
        btn_valoracion: "VALORA LA ATENCIÓN DE TU ASESOR",
        btn_finalizar: "FINALIZAR Y ENVIAR",
        btn_compartir_experiencia: "Compré en ZENITH CAR. ¡Excelente experiencia! Te la comparto.",
        footer_producido: "PRODUCIDO POR \"PIDE YA\" CARD",
        modal_evolucion_titulo: "VIVE LA EVOLUCIÓN",
        modal_evolucion_subtitulo: "Descubre lo que nos hace diferentes",
        btn_lujo: "EL LUJO QUE MERECES",
        btn_tecnologia: "TECNOLOGÍA E INNOVACIÓN",
        btn_momento: "ESTE ES TU MOMENTO",
        btn_asistencia: "ASISTENCIA ESPECIALIZADA",
        faq_titulo: "PREGUNTAS FRECUENTES",
        faq_q1: "¿Qué incluye la compra o renta de un vehículo?",
        faq_r1: "Todos nuestros vehículos incluyen garantía de agencia, tanque lleno de cortesía, kit de seguridad vial y un detallado riguroso antes de la entrega.",
        faq_q2: "¿Dónde se encuentran las instalaciones o el punto de entrega?",
        faq_r2: "Nuestra sala de exhibición principal y área de entregas están ubicadas en el showroom principal. Las instrucciones detalladas se envían vía WhatsApp al agendar su cita.",
        faq_q3: "¿Cuál es la política de cancelación o devolución de apartado?",
        faq_r3: "Se aplican reembolsos completos en caso de cancelación del trámite crediticio o si se solicita la anulación al menos 48 horas antes de la firma del contrato.",
        faq_q4: "¿Cómo puedo apartar o financiar un automóvil?",
        faq_r4: "Puede asegurar su unidad con un depósito inicial mediante tarjeta o transferencia bancaria, y liquidar o iniciar su plan de financiamiento al momento de la entrega.",
        faq_q5: "¿Ofrecen opciones de prueba de manejo (Test Drive)?",
        faq_r5: "¡Por supuesto! Contamos con pruebas de manejo disponibles para todos nuestros modelos vigentes, con previa cita y licencia de conducir vigente.",
        contact_titulo: "CONTACTO",
        contact_sub: "¡Síguenos en nuestras redes y canales oficiales!",
        btn_wsp: "CHAT EN WHATSAPP",
        btn_web: "SITIO WEB OFICIAL",
        btn_fb: "FACEBOOK OFICIAL",
        btn_ig: "INSTAGRAM",
        qr_titulo: "ESCANEA EL CÓDIGO QR",
        btn_qr: "COMPARTIR QR",
        cat1_t: "QUIÉNES SOMOS",
        cat1_c: "ZENITH CAR redefine la movilidad premium en la región, ofreciendo vehículos de alta ingeniería, deportividad pura, seguridad de vanguardia y un diseño sofisticado que eleva la experiencia de conducción diaria al verdadero placer de conducir.",
        cat2_t: "EXCELENCIA",
        cat2_c: "Explora nuestra gama de servicios automotrices premium: Venta de vehículos nuevos de la línea ZENITH CAR, planes de financiamiento corporativos y a tu medida, pruebas de manejo personalizadas, taller mecánico de alta especialización y venta de refacciones originales.",
        cat3_t: "CLIENTES FELICES",
        cat3_c: "Nuestra prioridad es la excelencia en el servicio. Conductores y familias de Aguascalientes respaldan la calidad, el confort y el desempeño excepcional que solo la ingeniería avanzada y la deportividad de ZENITH CAR pueden ofrecer.",
        header_asistente_titulo: "Asistente Personalizado",
        header_asistente_bienvenida: "¡Bienvenido/a! Permítenos ayudarte a encontrar al especialista ideal para ti. Solo te tomará unos segundos responder unas breves preguntas.",
        paso1_titulo: "PASO 1. Datos básicos del prospecto",
        paso1_desc: "Estos datos permiten dar seguimiento oportuno.",
        label_nombre: "Nombre completo *",
        label_whatsapp: "WhatsApp *",
        label_correo: "Correo electrónico (opcional)",
        label_contacto: "¿Cómo prefieres que te contactemos?",
        btn_wsp_contacto: "WhatsApp",
        btn_llamada: "Llamada",
        btn_correo_contacto: "Correo",
        btn_regresar: "Regresar al Menú",
        resena_titulo: "Evaluación de Servicio (Confidencial)",
        resena_desc: "Elige a tu asesor para enviar tu calificación directamente a la Gerencia de Ventas.",
        paso2_titulo: "PASO 2. ¿Qué vehículo te interesa?",
        paso2_desc: "Informa al asesor qué modelos generan más interés en el mercado.",
        btn_modelo_sedan: "Sedán / Compacto",
        btn_modelo_suv: "SUV / Camioneta",
        btn_modelo_deportivo: "Deportivo",
        btn_modelo_pickup: "Pick-up",
        btn_modelo_hibrido: "Híbrido o Eléctrico",
        btn_modelo_nose: "Aún no lo sé",
        paso3_titulo: "PASO 3. ¿Qué tipo de vehículo buscas?",
        paso3_desc: "Perfilado inicial de la silueta automotriz.",
        btn_tipo_suv: "SUV",
        btn_tipo_sedan: "Sedán",
        btn_tipo_deportivo: "Deportivo",
        btn_tipo_electrico: "Eléctrico",
        btn_tipo_hibrido: "Híbrido",
        btn_tipo_familiar: "Familiar",
        btn_tipo_ejecutivo: "Ejecutivo",
        btn_tipo_otro: "Otro",
        paso4_titulo: "PASO 4. ¿Para qué lo utilizarás principalmente?",
        paso4_desc: "Segmentación de la utilidad técnica comercial.",
        btn_uso_personal: "Uso personal",
        btn_uso_familiar: "Uso familiar",
        btn_uso_empresa: "Empresa",
        btn_uso_uber: "Uber / Didi Exec",
        btn_uso_viajes: "Viajes",
        btn_uso_trabajo: "Trabajo",
        btn_uso_otro: "Otro",
        paso5_titulo: "PASO 5. ¿Cuándo planeas comprar?",
        paso5_desc: "Esta métrica de urgencia es oro para la gerencia.",
        btn_tiempo_semana: "Esta semana",
        btn_tiempo_mes: "Este mes",
        btn_tiempo_3meses: "Dentro de 3 meses",
        btn_tiempo_6meses: "Dentro de 6 meses",
        btn_tiempo_investigando: "Solo estoy investigando",
        btn_anterior: "Anterior",
        btn_siguiente: "Siguiente",
        paso6_titulo: "PASO 6. ¿Cómo piensas adquirirlo?",
        paso6_desc: "Perfilado del esquema financiero.",
        btn_metodo_contado: "Contado",
        btn_metodo_credito: "Crédito",
        btn_metodo_arrendamiento: "Arrendamiento",
        btn_metodo_nose: "Aún no lo sé",
        paso7_titulo: "PASO 7. ¿Qué presupuesto aproximado tienes?",
        paso7_desc: "Clasificación del poder adquisitivo.",
        paso8_titulo: "PASO 8. ¿Qué promoción te llamó más la atención?",
        paso8_desc: "Mide directamente la efectividad de las campañas activas.",
        btn_promo_verano: "Bono de verano",
        btn_promo_tasa: "Tasa 8.99%",
        btn_promo_seguro: "Seguro gratis",
        btn_promo_mantenimiento: "Mantenimiento incluido",
        btn_promo_test: "Test Drive (Prueba de manejo)",
        btn_promo_otro: "Otro",
        paso9_titulo: "PASO 9. ¿Cómo conociste nuestra AGENCIA?",
        paso9_desc: "Auditoría pura de Retorno de Inversión (ROI) en publicidad.",
        btn_origen_asesor: "Mi asesor",
        btn_origen_amigo: "Un amigo",
        btn_origen_fb: "Facebook",
        btn_origen_ig: "Instagram",
        btn_origen_wa: "WhatsApp",
        btn_origen_google: "Google",
        btn_origen_web: "Sitio web",
        btn_origen_qr: "Código QR",
        btn_origen_otro: "Otro",
        paso10_titulo: "PASO 10. Asesor Sugerido",
        paso10_desc: "Con la información que nos diste, te sugerimos al asesor da clic en su pestaña:",
        paso10_cambiar: "Pero si prefieres, puedes cambiarlo aquí:",
        btn_finalizar: "FINALIZAR Y ENVIAR",
        titulo_asesor_digital: "Contacta a tu Asesor Digital",
        desc_asesor_digital: "Elige al asesor de tu preferencia para recibir atención inmediata / Da clic a su nombre.",
        btn_como_llegar: "CÓMO LLEGAR",
        btn_cerrar: "Cerrar",
        footer_producido: "PRODUCIDO POR",
        gerente_titulo_principal: "Agencia de Autos - Control de Auditoría",
        btn_salir: "Salir",
        gerente_html_title: "Panel Gerencial - Control de Leads Agencia",
        gerente_login_titulo: "Dirección Comercial",
        gerente_login_desc: "Ingrese la clave gerencial de auditoría",
        gerente_placeholder_clave: "Clave de acceso...",
        gerente_btn_ingresar: "Ingresar al Panel",
        gerente_titulo_principal: "Agencia de Autos - Control de Auditoría",
        btn_salir: "Salir",
        gerente_html_title: "Panel Gerencial - Control de Leads Agencia",
        gerente_login_titulo: "Dirección Comercial",
        gerente_login_desc: "Ingrese la clave gerencial de auditoría",
        gerente_placeholder_clave: "Clave de acceso...",
        gerente_btn_ingresar: "Ingresar al Panel",
        gerente_titulo_principal: "Agencia de Autos - Control de Auditoría",
        btn_salir: "Salir",
        gerente_kpi_total: "Total Prospectos",
        gerente_kpi_verde: "Avanzar Ya (Verde)",
        gerente_kpi_amarillo: "En Seguimiento (Amarillo)",
        gerente_kpi_rojo: "Esperar Condiciones (Rojo)",
        gerente_seccion_estatus: "Estatus de Maduración del Cliente",
        gerente_html_title: "Panel Gerencial - Control de Leads Agencia",
        gerente_login_titulo: "Dirección Comercial",
        gerente_login_desc: "Ingrese la clave gerencial de auditoría",
        gerente_placeholder_clave: "Clave de acceso...",
        gerente_btn_ingresar: "Ingresar al Panel",
        gerente_titulo_principal: "Agencia de Autos - Control de Auditoría",
        btn_salir: "Salir",
        gerente_kpi_total: "Total Prospectos",
        gerente_kpi_verde: "Avanzar Ya (Verde)",
        gerente_kpi_amarillo: "En Seguimiento (Amarillo)",
        gerente_kpi_rojo: "Esperar Condiciones (Rojo)",
        gerente_seccion_estatus: "Estatus de Maduración del Cliente",
        gerente_btn_excel: "Descargar Excel (CSV)",
        gerente_btn_limpiar: "Limpiar Panel",
        gerente_th_estado: "ESTADO",
        gerente_th_cliente: "CLIENTE / PROSPECTO",
        gerente_th_contacto: "TELÉFONO / CONTACTO",
        gerente_th_asesor: "ASESOR ASIGNADO",
        gerente_th_fecha: "PRIMER CONTACTO / FECHA",
        gerente_th_intentos: "INTENTOS DE SEGUIMIENTO",
        gerente_html_title: "Panel Gerencial - Control de Leads Agencia",
        gerente_login_titulo: "Dirección Comercial",
        gerente_login_desc: "Ingrese la clave gerencial de auditoría",
        gerente_placeholder_clave: "Clave de acceso...",
        gerente_btn_ingresar: "Ingresar al Panel",
        gerente_titulo_principal: "Agencia de Autos - Control de Auditoría",
        btn_salir: "Salir",
        gerente_kpi_total: "Total Prospectos",
        gerente_kpi_verde: "Avanzar Ya (Verde)",
        gerente_kpi_amarillo: "En Seguimiento (Amarillo)",
        gerente_kpi_rojo: "Esperar Condiciones (Rojo)",
        gerente_seccion_estatus: "Estatus de Maduración del Cliente",
        gerente_btn_excel: "Descargar Excel (CSV)",
        gerente_btn_limpiar: "Limpiar Panel",
        gerente_th_estado: "ESTADO",
        gerente_th_cliente: "CLIENTE / PROSPECTO",
        gerente_th_contacto: "TELÉFONO / CONTACTO",
        gerente_th_asesor: "ASESOR ASIGNADO",
        gerente_th_fecha: "PRIMER CONTACTO / FECHA",
        gerente_th_intentos: "INTENTOS DE SEGUIMIENTO",
        gerente_seccion_record: "Récord de Envíos de Enlace por Asesor",
        gerente_th_asesor_nombre: "ASESOR",
        gerente_th_total_envios: "TOTAL DE ENVÍOS / COMPARTIDOS",
        gerente_seccion_reseñas: "Evaluaciones Confidenciales y Reseñas de Asesores",
        gerente_th_fecha_res: "FECHA",
        gerente_th_asesor_eval: "ASESOR EVALUADO",
        gerente_th_calificacion: "CALIFICACIÓN",
        gerente_th_comentario: "COMENTARIO DEL CLIENTE",
        alerta_calificacion_exito: "¡Calificación guardada con éxito para el panel gerencial!",
    alerta_vaciar_panel: "¿Estás seguro de vaciar el panel de auditoría por completo?",
    alerta_excel_vacio: "No hay registros de prospectos para exportar.",
    gerente_texto_envios: "envíos",
    gerente_texto_veces: "veces",
    status_green: "Adelante con la venta",
    status_yellow: "Seguimiento y alerta",
    status_red: "Alto total / Investigando",
    cat_btn_main: "CATÁLOGO DE MODELOS Y SERVICIOS", 
        cat_modal_title: "CATÁLOGO COMERCIAL", 
        cat_modal_subtitle: "Selecciona la sección de tu interés", 
        cat_btn_autos: "CATÁLOGO DE AUTOS", 
        cat_btn_servicios: "SERVICIOS PERSONALIZADOS",
        cat_btn_interes: "Me interesa",
        cat_btn_comentar: "Coméntanos",
        cat_desc_serv: "Atención personalizada y especializada.",
        cat_btn_main: "CATÁLOGO DE MODELOS Y SERVICIOS", 
        cat_modal_title: "CATÁLOGO COMERCIAL", 
        cat_modal_subtitle: "Selecciona la sección de tu interés", 
        cat_btn_autos: "CATÁLOGO DE AUTOS", 
        cat_btn_servicios: "SERVICIOS PERSONALIZADOS",
        cat_btn_interes: "Me interesa",
        cat_btn_comentar: "Coméntanos",
        cat_desc_serv: "Atención personalizada y especializada."
    },
    en: {
        titulo_app: "SIPVEC - Commercial Intelligence System",
        bienvenida: "WELCOME",
        menu_quienes: "ABOUT US",
        menu_excelencia: "EXCELLENCE",
        menu_asistente: "QUICK ASSISTANT & FAQ",
        menu_redes: "WHATSAPP & SOCIAL MEDIA",
        btn_evolucion: "VIDEOS / LIVE THE EVOLUTION WITH US",
        btn_asesor: "CHOOSE YOUR SPECIALIZED ADVISOR / MAPS!",
        btn_cuestionario: "Start Questionnaire",
        btn_valoracion: "RATE YOUR ADVISOR'S ATTENTION",
        btn_finalizar: "FINISH AND SUBMIT",
        btn_compartir_experiencia: "I bought at ZENITH CAR. Excellent experience! Sharing it with you.",
        footer_producido: "PRODUCED BY \"PIDE YA\" CARD",
        modal_evolucion_titulo: "LIVE THE EVOLUTION",
        modal_evolucion_subtitulo: "Discover what makes us different",
        btn_lujo: "THE LUXURY YOU DESERVE",
        btn_tecnologia: "TECHNOLOGY & INNOVATION",
        btn_momento: "THIS IS YOUR MOMENT",
        btn_asistencia: "SPECIALIZED ASSISTANCE",
        faq_titulo: "FREQUENTLY ASKED QUESTIONS",
        faq_q1: "What is included with the purchase or rental of a vehicle?",
        faq_r1: "All our vehicles include agency warranty, complimentary full tank of gas, road safety kit, and rigorous detailing prior to delivery.",
        faq_q2: "Where are the facilities or delivery point located?",
        faq_r2: "Our main showroom and delivery area are located at the primary showroom. Detailed instructions are sent via WhatsApp when scheduling your appointment.",
        faq_q3: "What is the cancellation or reservation refund policy?",
        faq_r3: "Full refunds apply in case of credit processing cancellation or if cancellation is requested at least 48 hours before contract signing.",
        faq_q4: "How can I reserve or finance a car?",
        faq_r4: "You can secure your unit with an initial deposit via card or bank transfer, and settle or start your financing plan at the time of delivery.",
        faq_q5: "Do you offer test drive options?",
        faq_r5: "Of course! We have test drives available for all current models, by appointment and with a valid driver's license.",
        contact_titulo: "CONTACT",
        contact_sub: "Follow us on our official networks and channels!",
        btn_wsp: "CHAT ON WHATSAPP",
        btn_web: "OFFICIAL WEBSITE",
        btn_fb: "OFFICIAL FACEBOOK",
        btn_ig: "INSTAGRAM",
        qr_titulo: "SCAN THE QR CODE",
        btn_qr: "SHARE QR",
        cat1_t: "ABOUT US",
        cat1_c: "ZENITH CAR redefines premium mobility in the region, offering high-engineering vehicles, pure sportiness, cutting-edge safety, and sophisticated design that elevates the daily driving experience into true driving pleasure.",
        cat2_t: "EXCELENCE",
        cat2_c: "Explore our range of premium automotive services: Sale of new ZENITH CAR line vehicles, customized and corporate financing plans, personalized test drives, highly specialized mechanical workshop, and original spare parts sales.",
        cat3_t: "HAPPY CLIENTS",
        cat3_c: "Our priority is service excellence. Drivers and families in Aguascalientes endorse the quality, comfort, and exceptional performance that only ZENITH CAR's advanced engineering and sportiness can offer.",
        header_asistente_titulo: "Personalized Assistant",
        header_asistente_bienvenida: "Welcome! Let us help you find the ideal specialist for you. It will only take a few seconds to answer a few brief questions.",
        paso1_titulo: "STEP 1. Prospect Basic Data",
        paso1_desc: "These details allow for timely follow-up.",
        label_nombre: "Full name *",
        label_whatsapp: "WhatsApp *",
        label_correo: "Email (optional)",
        label_contacto: "How would you prefer to be contacted?",
        btn_wsp_contacto: "WhatsApp",
        btn_llamada: "Call",
        btn_correo_contacto: "Email",
        btn_regresar: "Return to Menu",
        resena_titulo: "Service Evaluation (Confidential)",
        resena_desc: "Choose your advisor to send your rating directly to the Sales Management.",
        paso2_titulo: "STEP 2. What vehicle are you interested in?",
        paso2_desc: "Inform the advisor which models generate the most market interest.",
        btn_modelo_sedan: "Sedan / Compact",
        btn_modelo_suv: "SUV / Crossover",
        btn_modelo_deportivo: "Sport / High Performance",
        btn_modelo_pickup: "Pick-up",
        btn_modelo_hibrido: "Hybrid / Electric",
        btn_modelo_nose: "Not sure yet",
        paso3_titulo: "STEP 3. What type of vehicle are you looking for?",
        paso3_desc: "Initial profiling of the automotive silhouette.",
        btn_tipo_suv: "SUV",
        btn_tipo_sedan: "Sedan",
        btn_tipo_deportivo: "Sport",
        btn_tipo_electrico: "Electric",
        btn_tipo_hibrido: "Hybrid",
        btn_tipo_familiar: "Family",
        btn_tipo_ejecutivo: "Executive",
        btn_tipo_otro: "Other",
        paso4_titulo: "STEP 4. What will you use it for primarily?",
        paso4_desc: "Commercial technical utility segmentation.",
        btn_uso_personal: "Personal use",
        btn_uso_familiar: "Family use",
        btn_uso_empresa: "Company",
        btn_uso_uber: "Uber / Didi Exec",
        btn_uso_viajes: "Travel",
        btn_uso_trabajo: "Work",
        btn_uso_otro: "Other",
        paso5_titulo: "STEP 5. When do you plan to buy?",
        paso5_desc: "This urgency metric is gold for management.",
        btn_tiempo_semana: "This week",
        btn_tiempo_mes: "This month",
        btn_tiempo_3meses: "Within 3 months",
        btn_tiempo_6meses: "Within 6 months",
        btn_tiempo_investigando: "Just researching",
        btn_anterior: "Previous",
        btn_siguiente: "Next",
        paso6_titulo: "STEP 6. How do you plan to acquire it?",
        paso6_desc: "Financial scheme profiling.",
        btn_metodo_contado: "Cash payment",
        btn_metodo_credito: "Credit",
        btn_metodo_arrendamiento: "Leasing",
        btn_metodo_nose: "Not sure yet",
        paso7_titulo: "STEP 7. What is your approximate budget?",
        paso7_desc: "Purchasing power classification.",
        paso8_titulo: "STEP 8. Which promotion caught your attention the most?",
        paso8_desc: "Directly measures the effectiveness of active campaigns.",
        btn_promo_verano: "Summer Bonus",
        btn_promo_tasa: "8.99% Rate",
        btn_promo_seguro: "Free Insurance",
        btn_promo_mantenimiento: "Maintenance included",
        btn_promo_test: "Test Drive",
        btn_promo_otro: "Other",
        paso9_titulo: "STEP 9. How did you hear about our AGENCY?",
        paso9_desc: "Pure ROI audit for advertising.",
        btn_origen_asesor: "My advisor",
        btn_origen_amigo: "A friend",
        btn_origen_fb: "Facebook",
        btn_origen_ig: "Instagram",
        btn_origen_wa: "WhatsApp",
        btn_origen_google: "Google",
        btn_origen_web: "Website",
        btn_origen_qr: "QR Code",
        btn_origen_otro: "Other",
        paso10_titulo: "STEP 10. Suggested Advisor",
        paso10_desc: "Based on the information provided, we suggest this advisor. Click on their tab:",
        paso10_cambiar: "But if you prefer, you can change it here:",
        btn_finalizar: "FINISH AND SEND",
        titulo_asesor_digital: "Contact Your Digital Advisor",
        desc_asesor_digital: "Choose your preferred advisor for immediate assistance / Click on their name.",
        btn_como_llegar: "GETTING HERE",
        btn_cerrar: "Close",
        footer_producido: "PRODUCED BY",
        gerente_titulo_principal: "Car Dealership - Audit Control",
        btn_salir: "Log Out",
        gerente_html_title: "Management Panel - Agency Lead Control",
        gerente_login_titulo: "Commercial Direction",
        gerente_login_desc: "Enter the management audit key",
        gerente_placeholder_clave: "Access key...",
        gerente_btn_ingresar: "Enter Panel",
        gerente_titulo_principal: "Car Dealership - Audit Control",
        btn_salir: "Log Out",
        gerente_html_title: "Management Panel - Agency Lead Control",
        gerente_login_titulo: "Commercial Direction",
        gerente_login_desc: "Enter the management audit key",
        gerente_placeholder_clave: "Access key...",
        gerente_btn_ingresar: "Enter Panel",
        gerente_titulo_principal: "Car Dealership - Audit Control",
        btn_salir: "Log Out",
        gerente_kpi_total: "Total Leads",
        gerente_kpi_verde: "Proceed Now (Green)",
        gerente_kpi_amarillo: "In Follow-up (Yellow)",
        gerente_kpi_rojo: "Wait for Conditions (Red)",
        gerente_seccion_estatus: "Customer Maturation Status",
        gerente_html_title: "Management Panel - Agency Lead Control",
        gerente_login_titulo: "Commercial Direction",
        gerente_login_desc: "Enter the management audit key",
        gerente_placeholder_clave: "Access key...",
        gerente_btn_ingresar: "Enter Panel",
        gerente_titulo_principal: "Car Dealership - Audit Control",
        btn_salir: "Log Out",
        gerente_kpi_total: "Total Leads",
        gerente_kpi_verde: "Proceed Now (Green)",
        gerente_kpi_amarillo: "In Follow-up (Yellow)",
        gerente_kpi_rojo: "Wait for Conditions (Red)",
        gerente_seccion_estatus: "Customer Maturation Status",
        gerente_btn_excel: "Download Excel (CSV)",
        gerente_btn_limpiar: "Clear Panel",
        gerente_th_estado: "STATUS",
        gerente_th_cliente: "CLIENT / PROSPECT",
        gerente_th_contacto: "PHONE / CONTACT",
        gerente_th_asesor: "ASSIGNED ADVISOR",
        gerente_th_fecha: "FIRST CONTACT / DATE",
        gerente_th_intentos: "FOLLOW-UP ATTEMPTS",
        gerente_html_title: "Management Panel - Agency Lead Control",
        gerente_login_titulo: "Commercial Direction",
        gerente_login_desc: "Enter the management audit key",
        gerente_placeholder_clave: "Access key...",
        gerente_btn_ingresar: "Enter Panel",
        gerente_titulo_principal: "Car Dealership - Audit Control",
        btn_salir: "Log Out",
        gerente_kpi_total: "Total Leads",
        gerente_kpi_verde: "Proceed Now (Green)",
        gerente_kpi_amarillo: "In Follow-up (Yellow)",
        gerente_kpi_rojo: "Wait for Conditions (Red)",
        gerente_seccion_estatus: "Customer Maturation Status",
        gerente_btn_excel: "Download Excel (CSV)",
        gerente_btn_limpiar: "Clear Panel",
        gerente_th_estado: "STATUS",
        gerente_th_cliente: "CLIENT / PROSPECT",
        gerente_th_contacto: "PHONE / CONTACT",
        gerente_th_asesor: "ASSIGNED ADVISOR",
        gerente_th_fecha: "FIRST CONTACT / DATE",
        gerente_th_intentos: "FOLLOW-UP ATTEMPTS",
        gerente_seccion_record: "Link Submission Record by Advisor",
        gerente_th_asesor_nombre: "ADVISOR",
        gerente_th_total_envios: "TOTAL SUBMISSIONS / SHARES",
        gerente_seccion_reseñas: "Confidential Evaluations and Advisor Reviews",
        gerente_th_fecha_res: "DATE",
        gerente_th_asesor_eval: "EVALUATED ADVISOR",
        gerente_th_calificacion: "RATING",
        gerente_th_comentario: "CUSTOMER COMMENT",
        alerta_calificacion_exito: "Rating successfully saved for the management panel!",
    alerta_vaciar_panel: "Are you sure you want to completely clear the audit panel?",
    alerta_excel_vacio: "No lead records to export.",
    gerente_texto_envios: "submissions",
    gerente_texto_veces: "times",
    status_green: "Proceed with sale",
    status_yellow: "Follow-up and alert",
    status_red: "Full stop / Investigating",
    cat_btn_main: "MODELS AND SERVICES CATALOG", 
        cat_modal_title: "COMMERCIAL CATALOG", 
        cat_modal_subtitle: "Select the section of your interest", 
        cat_btn_autos: "CARS CATALOG", 
        cat_btn_servicios: "CUSTOMIZED SERVICES",
        cat_btn_interes: "I'm interested",
        cat_btn_comentar: "Contact us",
        cat_desc_serv: "Personalized and specialized attention.",
        cat_btn_main: "MODELS AND SERVICES CATALOG", 
        cat_modal_title: "COMMERCIAL CATALOG", 
        cat_modal_subtitle: "Select the section of your interest", 
        cat_btn_autos: "CARS CATALOG", 
        cat_btn_servicios: "CUSTOMIZED SERVICES",
        cat_btn_interes: "I'm interested",
        cat_btn_comentar: "Contact us",
        cat_desc_serv: "Personalized and specialized attention."
    },
    pt: {
        titulo_app: "SIPVEC - Sistema de Inteligência Comercial",
        bienvenida: "BEM-VINDOS",
        menu_quienes: "QUEM SOMOS",
        menu_excelencia: "EXCELÊNCIA",
        menu_asistente: "ASSISTENTE RÁPIDO E DÚVIDAS",
        menu_redes: "WHATSAPP E REDES SOCIAIS",
        btn_evolucion: "VÍDEOS / VIVA CONOSCO A EVOLUÇÃO",
        btn_asesor: "ESCOLHA SEU CONSULTOR ESPECIALIZADO / MAPS!",
        btn_cuestionario: "Iniciar Questionário",
        btn_valoracion: "AVALIE O ATENDIMENTO DO SEU CONSULTOR",
        btn_finalizar: "FINALIZAR E ENVIAR",
        btn_compartir_experiencia: "Comprei na ZENITH CAR. Excelente experiência! Compartilho com você.",
        footer_producido: "PRODUZIDO POR \"PIDE YA\" CARD",
        modal_evolucion_titulo: "VIVA A EVOLUÇÃO",
        modal_evolucion_subtitulo: "Descubra o que nos faz diferentes",
        btn_lujo: "O LUXO QUE VOCÊ MERECE",
        btn_tecnologia: "TECNOLOGIA E INOVAÇÃO",
        btn_momento: "ESTE É O SEU MOMENTO",
        btn_asistencia: "ASSISTÊNCIA ESPECIALIZADA",
        faq_titulo: "PERGUNTAS FREQUENTES",
        faq_q1: "O que está incluído na compra ou aluguel de um veículo?",
        faq_r1: "Todos os nossos veículos incluem garantia de fábrica, tanque cheio de cortesia, kit de segurança rodoviária e detalhamento rigoroso antes da entrega.",
        faq_q2: "Onde estão localizadas as instalações ou o ponto de entrega?",
        faq_r2: "Nosso showroom principal e área de entrega estão localizados no showroom principal. Instruções detalhadas são enviadas via WhatsApp ao agendar seu horário.",
        faq_q3: "Qual é a política de cancelamento ou reembolso de reserva?",
        faq_r3: "Reembolsos integrais aplicam-se em caso de cancelamento do processo de crédito ou se solicitado pelo menos 48 horas antes da assinatura do contrato.",
        faq_q4: "Como posso reservar ou financiar um carro?",
        faq_r4: "Você pode garantir sua unidade com um depósito inicial via cartão ou transferência bancária, e quitar ou iniciar seu plano de financiamento no momento da entrega.",
        faq_q5: "Vocês oferecem opções de test-drive?",
        faq_r5: "Com certeza! Temos test-drives disponíveis para todos os nossos modelos vigentes, mediante agendamento prévio e carteira de motorista válida.",
        contact_titulo: "CONTATO",
        contact_sub: "Siga-nos em nossas redes e canais oficiais!",
        btn_wsp: "CHAT NO WHATSAPP",
        btn_web: "SITE OFICIAL",
        btn_fb: "FACEBOOK OFICIAL",
        btn_ig: "INSTAGRAM",
        qr_titulo: "ESCANEIE O CÓDIGO QR",
        btn_qr: "COMPARTILHAR QR",
        cat1_t: "QUEM SOMOS",
        cat1_c: "A ZENITH CAR redefine a mobilidade premium na região, oferecendo veículos de alta engenharia, esportividade pura, segurança de vanguarda e um design sofisticado que eleva a experiência diária de condução ao verdadeiro prazer de dirigir.",
        cat2_t: "EXCELÊNCIA",
        cat2_c: "Explore nossa gama de serviços automotivos premium: Venda de novos veículos da linha ZENITH CAR, planos de financiamento corporativos e sob medida, test-drives personalizados, oficina mecânica altamente especializada e venda de peças originais.",
        cat3_t: "CLIENTES FELIZES",
        cat3_c: "Nossa prioridade é a excelência no atendimento. Motoristas e famílias de Aguascalientes endossam a qualidade, o conforto e o desempenho excepcional que apenas a engenharia avançada e a esportividade da ZENITH CAR podem oferecer.",
        header_asistente_titulo: "Assistente Personalizado",
        header_asistente_bienvenida: "Bem-vindo/a! Permita-nos ajudá-lo a encontrar o especialista ideal para você. Levará apenas alguns segundos para responder a algumas breves perguntas.",
        paso1_titulo: "PASSO 1. Dados Básicos do Prospecto",
        paso1_desc: "Estes dados permitem um acompanhamento oportuno.",
        label_nombre: "Nome completo *",
        label_whatsapp: "WhatsApp *",
        label_correo: "E-mail (opcional)",
        label_contacto: "Como prefere ser contatado?",
        btn_wsp_contacto: "WhatsApp",
        btn_llamada: "Chamada",
        btn_correo_contacto: "E-mail",
        btn_regresar: "Voltar ao Menu",
        resena_titulo: "Avaliação de Serviço (Confidencial)",
        resena_desc: "Escolha seu consultor para enviar sua avaliação diretamente à Gerência de Vendas.",
        paso2_titulo: "PASSO 2. Qual veículo te interessa?",
        paso2_desc: "Informe ao consultor quais modelos geram mais interesse no mercado.",
        btn_modelo_sedan: "Sedã / Compacto",
        btn_modelo_suv: "SUV / Camionete",
        btn_modelo_deportivo: "Esportivo",
        btn_modelo_pickup: "Pick-up",
        btn_modelo_hibrido: "Híbrido / Elétrico",
        btn_modelo_nose: "Ainda não sei",
        paso3_titulo: "PASSO 3. Que tipo de veículo você procura?",
        paso3_desc: "Perfil inicial da silhueta automotiva.",
        btn_tipo_suv: "SUV",
        btn_tipo_sedan: "Sedã",
        btn_tipo_deportivo: "Esportivo",
        btn_tipo_electrico: "Elétrico",
        btn_tipo_hibrido: "Híbrido",
        btn_tipo_familiar: "Familiar",
        btn_tipo_ejecutivo: "Executivo",
        btn_tipo_otro: "Outro",
        paso4_titulo: "PASSO 4. Para que você o utilizará principalmente?",
        paso4_desc: "Segmentação da utilidade técnica comercial.",
        btn_uso_personal: "Uso pessoal",
        btn_uso_familiar: "Uso familiar",
        btn_uso_empresa: "Empresa",
        btn_uso_uber: "Uber / Didi Exec",
        btn_uso_viajes: "Viagens",
        btn_uso_trabajo: "Trabalho",
        btn_uso_otro: "Outro",
        paso5_titulo: "PASSO 5. Quando você planeja comprar?",
        paso5_desc: "Esta métrica de urgência é ouro para a gerência.",
        btn_tiempo_semana: "Esta semana",
        btn_tiempo_mes: "Este mês",
        btn_tiempo_3meses: "Dentro de 3 meses",
        btn_tiempo_6meses: "Dentro de 6 meses",
        btn_tiempo_investigando: "Apenas pesquisando",
        btn_anterior: "Anterior",
        btn_siguiente: "Próximo",
        paso6_titulo: "PASSO 6. Como pretende adquirirlo?",
        paso6_desc: "Perfilamento do esquema financeiro.",
        btn_metodo_contado: "À vista",
        btn_metodo_credito: "Crédito",
        btn_metodo_arrendamiento: "Arrendamento",
        btn_metodo_nose: "Ainda não sei",
        paso7_titulo: "PASSO 7. Qual é o seu orçamento aproximado?",
        paso7_desc: "Classificação do poder de compra.",
        paso8_titulo: "PASSO 8. Qual promoção chamou mais a sua atenção?",
        paso8_desc: "Mede diretamente a eficácia das campanhas ativas.",
        btn_promo_verano: "Bônus de verão",
        btn_promo_tasa: "Taxa de 8,99%",
        btn_promo_seguro: "Seguro grátis",
        btn_promo_mantenimiento: "Manutenção inclusa",
        btn_promo_test: "Test Drive (Teste de direção)",
        btn_promo_otro: "Outro",
        paso9_titulo: "PASSO 9. Como conheceu a nossa AGÊNCIA?",
        paso9_desc: "Auditoria pura de Retorno sobre Investimento (ROI) em publicidade.",
        btn_origen_asesor: "Meu assessor",
        btn_origen_amigo: "Um amigo",
        btn_origen_fb: "Facebook",
        btn_origen_ig: "Instagram",
        btn_origen_wa: "WhatsApp",
        btn_origen_google: "Google",
        btn_origen_web: "Site",
        btn_origen_qr: "Código QR",
        btn_origen_otro: "Outro",
        paso10_titulo: "PASSO 10. Assessor Sugerido",
        paso10_desc: "Com as informações que nos deu, sugerimos o assessor. Clique na aba dele:",
        paso10_cambiar: "Mas se preferir, pode alterar aqui:",
        btn_finalizar: "FINALIZAR E ENVIAR",
        titulo_asesor_digital: "Contate seu Assessor Digital",
        desc_asesor_digital: "Escolha o assessor de sua preferência para atendimento imediato / Clique no nome dele.",
        btn_como_llegar: "COMO CHEGAR",
        btn_cerrar: "Fechar",
        footer_producido: "PRODUZIDO POR",
        gerente_titulo_principal: "Concessionária - Controle de Auditoria",
        btn_salir: "Sair",
        gerente_html_title: "Painel Gerencial - Controle de Leads da Agência",
        gerente_login_titulo: "Direção Comercial",
        gerente_login_desc: "Insira a chave gerencial de auditoria",
        gerente_placeholder_clave: "Chave de acesso...",
        gerente_btn_ingresar: "Entrar no Painel",
        gerente_titulo_principal: "Concessionária - Controle de Auditoria",
        btn_salir: "Sair",
        gerente_html_title: "Painel Gerencial - Controle de Leads da Agência",
        gerente_login_titulo: "Direção Comercial",
        gerente_login_desc: "Insira a chave gerencial de auditoria",
        gerente_placeholder_clave: "Chave de acesso...",
        gerente_btn_ingresar: "Entrar no Painel",
        gerente_titulo_principal: "Concessionária - Controle de Auditoria",
        btn_salir: "Sair",
        gerente_kpi_total: "Total de Leads",
        gerente_kpi_verde: "Avançar Já (Verde)",
        gerente_kpi_amarillo: "Em Acompanhamento (Amarelo)",
        gerente_kpi_rojo: "Aguardar Condições (Vermelho)",
        gerente_seccion_estatus: "Status de Maturação do Cliente",
        gerente_html_title: "Painel Gerencial - Controle de Leads da Agência",
        gerente_login_titulo: "Direção Comercial",
        gerente_login_desc: "Insira a chave gerencial de auditoria",
        gerente_placeholder_clave: "Chave de acesso...",
        gerente_btn_ingresar: "Entrar no Painel",
        gerente_titulo_principal: "Concessionária - Controle de Auditoria",
        btn_salir: "Sair",
        gerente_kpi_total: "Total de Leads",
        gerente_kpi_verde: "Avançar Já (Verde)",
        gerente_kpi_amarillo: "Em Acompanhamento (Amarelo)",
        gerente_kpi_rojo: "Aguardar Condições (Vermelho)",
        gerente_seccion_estatus: "Status de Maturação do Cliente",
        gerente_btn_excel: "Baixar Excel (CSV)",
        gerente_btn_limpiar: "Limpar Painel",
        gerente_th_estado: "STATUS",
        gerente_th_cliente: "CLIENTE / PROSPECTO",
        gerente_th_contacto: "TELEFONE / CONTATO",
        gerente_th_asesor: "ASSESSOR ATRIBUÍDO",
        gerente_th_fecha: "PRIMEIRO CONTATO / DATA",
        gerente_th_intentos: "TENTATIVAS DE ACOMPANHAMENTO",
        gerente_html_title: "Painel Gerencial - Controle de Leads da Agência",
        gerente_login_titulo: "Direção Comercial",
        gerente_login_desc: "Insira a chave gerencial de auditoria",
        gerente_placeholder_clave: "Chave de acesso...",
        gerente_btn_ingresar: "Entrar no Painel",
        gerente_titulo_principal: "Concessionária - Controle de Auditoria",
        btn_salir: "Sair",
        gerente_kpi_total: "Total de Leads",
        gerente_kpi_verde: "Avançar Já (Verde)",
        gerente_kpi_amarillo: "Em Acompanhamento (Amarelo)",
        gerente_kpi_rojo: "Aguardar Condições (Vermelho)",
        gerente_seccion_estatus: "Status de Maturação do Cliente",
        gerente_btn_excel: "Baixar Excel (CSV)",
        gerente_btn_limpiar: "Limpar Painel",
        gerente_th_estado: "STATUS",
        gerente_th_cliente: "CLIENTE / PROSPECTO",
        gerente_th_contacto: "TELEFONE / CONTATO",
        gerente_th_asesor: "ASSESSOR ATRIBUÍDO",
        gerente_th_fecha: "PRIMEIRO CONTATO / DATA",
        gerente_th_intentos: "TENTATIVAS DE ACOMPANHAMENTO",
        gerente_seccion_record: "Recorde de Envios de Link por Assessor",
        gerente_th_asesor_nombre: "ASSESSOR",
        gerente_th_total_envios: "TOTAL DE ENVIOS / COMPARTILHAMENTOS",
        gerente_seccion_reseñas: "Avaliações Confidenciais e Resenhas de Assessores",
        gerente_th_fecha_res: "DATA",
        gerente_th_asesor_eval: "ASSESSOR AVALIADO",
        gerente_th_calificacion: "CLASSIFICAÇÃO",
        gerente_th_comentario: "COMENTÁRIO DO CLIENTE",
        alerta_calificacion_exito: "Avaliação salva com sucesso para o painel gerencial!",
    alerta_vaciar_panel: "Tem certeza de que deseja limpar completamente o painel de auditoria?",
    alerta_excel_vacio: "Não há registros de leads para exportar.",
    gerente_texto_envios: "envios",
    gerente_texto_veces: "vezes",
    status_green: "Prosseguir com a venda",
    status_yellow: "Acompanhamento e alerta",
    status_red: "Parada total / Investigando",
    cat_btn_main: "CATÁLOGO DE MODELOS E SERVIÇOS", 
        cat_modal_title: "CATÁLOGO COMERCIAL", 
        cat_modal_subtitle: "Selecione a seção de seu interesse", 
        cat_btn_autos: "CATÁLOGO DE CARROS", 
        cat_btn_servicios: "SERVIÇOS PERSONALIZADOS",
        cat_btn_interes: "Tenho interesse",
        cat_btn_comentar: "Fale conosco",
        cat_desc_serv: "Atendimento personalizado e especializado.",
        cat_btn_main: "CATÁLOGO DE MODELOS E SERVIÇOS", 
        cat_modal_title: "CATÁLOGO COMERCIAL", 
        cat_modal_subtitle: "Selecione a seção de seu interesse", 
        cat_btn_autos: "CATÁLOGO DE CARROS", 
        cat_btn_servicios: "SERVIÇOS PERSONALIZADOS",
        cat_btn_interes: "Tenho interesse",
        cat_btn_comentar: "Fale conosco",
        cat_desc_serv: "Atendimento personalizado e especializado."
    },
    fr: {
        titulo_app: "SIPVEC - Système d'Intelligence Commerciale",
        bienvenida: "BIENVENUE",
        menu_quienes: "QUI SOMMES-NOUS",
        menu_excelencia: "EXCELLENCE",
        menu_asistente: "ASSISTANT RAPIDE & FAQ",
        menu_redes: "WHATSAPP & RÉSEAUX SOCIAUX",
        btn_evolucion: "VIDÉOS / VIVEZ L'ÉVOLUTION AVEC NOUS",
        btn_asesor: "CHOISISSEZ VOTRE CONSEILLER SPÉCIALISÉ / MAPS !",
        btn_cuestionario: "Commencer le Questionnaire",
        btn_valoracion: "ÉVALUEZ L'ATTENTION DE VOTRE CONSEILLER",
        btn_finalizar: "TERMINER ET ENVOYER",
        btn_compartir_experiencia: "J'ai acheté chez ZENITH CAR. Excellente expérience ! Je la partage avec vous.",
        footer_producido: "PRODUIT PAR \"PIDE YA\" CARD",
        modal_evolucion_titulo: "VIVEZ L'ÉVOLUTION",
        modal_evolucion_subtitulo: "Découvrez ce qui nous rend différents",
        btn_lujo: "LE LUXE QUE VOUS MÉRITEZ",
        btn_tecnologia: "TECHNOLOGIE ET INNOVATION",
        btn_momento: "C'EST VOTRE MOMENT",
        btn_asistencia: "ASSISTANCE SPÉCIALISÉE",
        faq_titulo: "QUESTIONS FRÉQUEMMENT POSÉES",
        faq_q1: "Que comprend l'achat ou la location d'un véhicule ?",
        faq_r1: "Tous nos véhicules comprennent une garantie constructeur, un plein de carburant de courtoisie, un kit de sécurité routière et un detailing rigoureux avant la livraison.",
        faq_q2: "Où se trouvent les installations ou le point de livraison ?",
        faq_r2: "Notre showroom principal et notre zone de livraison sont situés dans le showroom principal. Des instructions détaillées sont envoyées via WhatsApp lors de la prise de rendez-vous.",
        faq_q3: "Quelle est la politique d'annulation ou de remboursement des arrhes ?",
        faq_r3: "Des remboursements intégraux s'appliquent en cas d'annulation du dossier de crédit ou si l'annulation est demandée au moins 48 heures avant la signature du contrat.",
        faq_q4: "Comment puis-je réserver ou financer une voiture ?",
        faq_r4: "Vous pouvez sécuriser votre véhicule avec un dépôt initial par carte ou virement bancaire, et solder ou démarrer votre plan de financement au moment de la livraison.",
        faq_q5: "Proposez-vous des options d'essai routier (Test Drive) ?",
        faq_r5: "Bien sûr ! Nous proposons des essais routiers pour tous nos modèles actuels, sur rendez-vous et avec un permis de conduire valide.",
        contact_titulo: "CONTACT",
        contact_sub: "Suivez-nous sur nos réseaux et canaux officiels !",
        btn_wsp: "CHAT WHATSAPP",
        btn_web: "SITE OFFICIEL",
        btn_fb: "FACEBOOK OFFICIEL",
        btn_ig: "INSTAGRAM",
        qr_titulo: "SCANNEZ LE CODE QR",
        btn_qr: "PARTAGER LE QR",
        cat1_t: "QUI SOMMES-NOUS",
        cat1_c: "ZENITH CAR redéfinit la mobilité premium dans la région, en proposant des véhicules de haute ingénierie, une sportivité pure, une sécurité de pointe et un design sophistiqué qui élève l'expérience de conduite quotidienne au rang de véritable plaisir.",
        cat2_t: "EXCELLENCE",
        cat2_c: "Explorez notre gamme de services automobiles premium : Vente de véhicules neufs de la ligne ZENITH CAR, plans de financement d'entreprise et sur mesure, essais routiers personnalisés, atelier mécanique hautement spécialisé et vente de pièces d'origine.",
        cat3_t: "CLIENTS HEUREUX",
        cat3_c: "Notre priorité est l'excellence du service. Les conducteurs et les familles d'Aguascalientes soutiennent la qualité, le confort et les performances exceptionnelles que seule l'ingénierie avancée et la sportivité de ZENITH CAR peuvent offrir.",
        header_asistente_titulo: "Assistant Personnalisé",
        header_asistente_bienvenida: "Bienvenue ! Laissez-nous vous aider à trouver le spécialiste idéal. Cela ne prendra que quelques secondes pour répondre à de brèves questions.",
        paso1_titulo: "ÉTAPE 1. Données de base du prospect",
        paso1_desc: "Ces informations permettent un suivi rapide.",
        label_nombre: "Nom complet *",
        label_whatsapp: "WhatsApp *",
        label_correo: "E-mail (facultatif)",
        label_contacto: "Comment préférez-vous être contacté ?",
        btn_wsp_contacto: "WhatsApp",
        btn_llamada: "Appel",
        btn_correo_contacto: "E-mail",
        btn_regresar: "Retour au Menu",
        resena_titulo: "Évaluation du service (Confidentiel)",
        resena_desc: "Choisissez votre conseiller pour envoyer votre note directement à la Direction des Ventes.",
        paso2_titulo: "ÉTAPE 2. Quel véhicule vous intéresse ?",
        paso2_desc: "Informez le conseiller des modèles qui suscitent le plus d'intérêt.",
        btn_modelo_sedan: "Berline / Compacte",
        btn_modelo_suv: "SUV / Crossover",
        btn_modelo_deportivo: "Sportive",
        btn_modelo_pickup: "Pick-up",
        btn_modelo_hibrido: "Hybride / Électrique",
        btn_modelo_nose: "Je ne sais pas encore",
        paso3_titulo: "ÉTAPE 3. Quel type de véhicule recherchez-vous ?",
        paso3_desc: "Profilage initial de la silhouette automobile.",
        btn_tipo_suv: "SUV",
        btn_tipo_sedan: "Berline",
        btn_tipo_deportivo: "Sportive",
        btn_tipo_electrico: "Électrique",
        btn_tipo_hibrido: "Hybride",
        btn_tipo_familiar: "Familiale",
        btn_tipo_ejecutivo: "Exécutive",
        btn_tipo_otro: "Autre",
        paso4_titulo: "ÉTAPE 4. À quoi l'utiliserez-vous principalement ?",
        paso4_desc: "Segmentation de l'utilité technique commerciale.",
        btn_uso_personal: "Usage personnel",
        btn_uso_familiar: "Usage familial",
        btn_uso_empresa: "Entreprise",
        btn_uso_uber: "Uber / Didi Exec",
        btn_uso_viajes: "Voyages",
        btn_uso_trabajo: "Travail",
        btn_uso_otro: "Autre",
        paso5_titulo: "ÉTAPE 5. Quand prévoyez-vous d'acheter ?",
        paso5_desc: "Cette métrique d'urgence est en or pour la direction.",
        btn_tiempo_semana: "Cette semaine",
        btn_tiempo_mes: "Ce mois-ci",
        btn_tiempo_3meses: "D'ici 3 mois",
        btn_tiempo_6meses: "D'ici 6 mois",
        btn_tiempo_investigando: "Je me renseigne seulement",
        btn_anterior: "Précédent",
        btn_siguiente: "Suivant",
        paso6_titulo: "ÉTAPE 6. Comment prévoyez-vous de l'acquérir ?",
        paso6_desc: "Profilage du schéma financier.",
        btn_metodo_contado: "Comptant",
        btn_metodo_credito: "Crédit",
        btn_metodo_arrendamiento: "Crédit-bail (Leasing)",
        btn_metodo_nose: "Je ne sais pas encore",
        paso7_titulo: "ÉTAPE 7. Quel est votre budget approximatif ?",
        paso7_desc: "Classification du pouvoir d'achat.",
        paso8_titulo: "ÉTAPE 8. Quelle promotion a le plus retenu votre attention ?",
        paso8_desc: "Mesure directement l'efficacité des campagnes en cours.",
        btn_promo_verano: "Bonus d'été",
        btn_promo_tasa: "Taux 8,99 %",
        btn_promo_seguro: "Assurance gratuite",
        btn_promo_mantenimiento: "Entretien inclus",
        btn_promo_test: "Essai routier (Test Drive)",
        btn_promo_otro: "Autre",
        paso9_titulo: "ÉTAPE 9. Comment avez-vous connu notre AGENCE ?",
        paso9_desc: "Audit pur du Retour sur Investissement (ROI) publicitaire.",
        btn_origen_asesor: "Mon conseiller",
        btn_origen_amigo: "Un ami",
        btn_origen_fb: "Facebook",
        btn_origen_ig: "Instagram",
        btn_origen_wa: "WhatsApp",
        btn_origen_google: "Google",
        btn_origen_web: "Site web",
        btn_origen_qr: "Code QR",
        btn_origen_otro: "Autre",
        paso10_titulo: "ÉTAPE 10. Conseiller suggéré",
        paso10_desc: "Avec les informations fournies, nous vous suggérons ce conseiller. Cliquez sur son onglet :",
        paso10_cambiar: "Mais si vous préférez, vous pouvez le changer ici :",
        btn_finalizar: "TERMINER ET ENVOYER",
        titulo_asesor_digital: "Contactez votre Conseiller Numérique",
        desc_asesor_digital: "Choisissez le conseiller de votre choix pour une assistance immédiate / Cliquez sur son nom.",
        btn_como_llegar: "COMMENT VENIR",
        btn_cerrar: "Fermer",
        footer_producido: "PRODUIT PAR",
        gerente_titulo_principal: "Concessionnaire Automobile - Contrôle d'Audit",
        btn_salir: "Quitter",
        gerente_html_title: "Panneau de Gestion - Contrôle des Leads de l'Agence",
        gerente_login_titulo: "Direction Commerciale",
        gerente_login_desc: "Entrez la clé de gestion de l'audit",
        gerente_placeholder_clave: "Clé d'accès...",
        gerente_btn_ingresar: "Entrer dans le Panneau",
        gerente_titulo_principal: "Concession Automobile - Contrôle d'Audit",
        btn_salir: "Quitter",
        gerente_html_title: "Panneau de Gestion - Contrôle des Leads de l'Agence",
        gerente_login_titulo: "Direction Commerciale",
        gerente_login_desc: "Entrez la clé de gestion de l'audit",
        gerente_placeholder_clave: "Clé d'accès...",
        gerente_btn_ingresar: "Entrer dans le Panneau",
        gerente_titulo_principal: "Concession Automobile - Contrôle d'Audit",
        btn_salir: "Quitter",
        gerente_kpi_total: "Total des Leads",
        gerente_kpi_verde: "Avancer Maintenant (Vert)",
        gerente_kpi_amarillo: "En Suivi (Jaune)",
        gerente_kpi_rojo: "Attendre les Conditions (Rouge)",
        gerente_seccion_estatus: "Statut de Maturation du Client",
        gerente_html_title: "Panneau de Gestion - Contrôle des Leads de l'Agence",
        gerente_login_titulo: "Direction Commerciale",
        gerente_login_desc: "Entrez la clé de gestion de l'audit",
        gerente_placeholder_clave: "Clé d'accès...",
        gerente_btn_ingresar: "Entrer dans le Panneau",
        gerente_titulo_principal: "Concession Automobile - Contrôle d'Audit",
        btn_salir: "Quitter",
        gerente_kpi_total: "Total des Leads",
        gerente_kpi_verde: "Avancer Maintenant (Vert)",
        gerente_kpi_amarillo: "En Suivi (Jaune)",
        gerente_kpi_rojo: "Attendre les Conditions (Rouge)",
        gerente_seccion_estatus: "Statut de Maturation du Client",
        gerente_btn_excel: "Télécharger Excel (CSV)",
        gerente_btn_limpiar: "Effacer le Panneau",
        gerente_th_estado: "STATUT",
        gerente_th_cliente: "CLIENT / PROSPECT",
        gerente_th_contacto: "TÉLÉPHONE / CONTACT",
        gerente_th_asesor: "CONSEILLER ASSIGNÉ",
        gerente_th_fecha: "PREMIER CONTACT / DATE",
        gerente_th_intentos: "TENTATIVES DE SUIVI",
        gerente_html_title: "Panneau de Gestion - Contrôle des Leads de l'Agence",
        gerente_login_titulo: "Direction Commerciale",
        gerente_login_desc: "Entrez la clé de gestion de l'audit",
        gerente_placeholder_clave: "Clé d'accès...",
        gerente_btn_ingresar: "Entrer dans le Panneau",
        gerente_titulo_principal: "Concession Automobile - Contrôle d'Audit",
        btn_salir: "Quitter",
        gerente_kpi_total: "Total des Leads",
        gerente_kpi_verde: "Avancer Maintenant (Vert)",
        gerente_kpi_amarillo: "En Suivi (Jaune)",
        gerente_kpi_rojo: "Attendre les Conditions (Rouge)",
        gerente_seccion_estatus: "Statut de Maturation du Client",
        gerente_btn_excel: "Télécharger Excel (CSV)",
        gerente_btn_limpiar: "Effacer le Panneau",
        gerente_th_estado: "STATUT",
        gerente_th_cliente: "CLIENT / PROSPECT",
        gerente_th_contacto: "TÉLÉPHONE / CONTACT",
        gerente_th_asesor: "CONSEILLER ASSIGNÉ",
        gerente_th_fecha: "PREMIER CONTACT / DATE",
        gerente_th_intentos: "TENTATIVES DE SUIVI",
        gerente_seccion_record: "Record d'Envois de Liens par Conseiller",
        gerente_th_asesor_nombre: "CONSEILLER",
        gerente_th_total_envios: "TOTAL DES ENVOIS / PARTAGES",
        gerente_seccion_reseñas: "Évaluations Confidentielles et Avis des Conseillers",
        gerente_th_fecha_res: "DATE",
        gerente_th_asesor_eval: "CONSEILLER ÉVALUÉ",
        gerente_th_calificacion: "NOTE",
        gerente_th_comentario: "COMMENTAIRE DU CLIENT",
        alerta_calificacion_exito: "Évaluation enregistrée avec succès pour le panneau de gestion !",
    alerta_vaciar_panel: "Êtes-vous sûr de vouloir vider complètement le panneau d'audit ?",
    alerta_excel_vacio: "Aucun enregistrement de lead à exporter.",
    gerente_texto_envios: "envois",
    gerente_texto_veces: "fois",
    status_green: "Procéder à la vente",
    status_yellow: "Suivi et alerte",
    status_red: "Arrêt complet / Enquête",
    cat_btn_main: "CATALOGUE DE MODÈLES ET SERVICES", 
        cat_modal_title: "CATALOGUE COMMERCIAL", 
        cat_modal_subtitle: "Sélectionnez la section de votre intérêt", 
        cat_btn_autos: "CATALOGUE DE VOITURES", 
        cat_btn_servicios: "SERVICES PERSONNALISÉS",
        cat_btn_interes: "Ça m'intéresse",
        cat_btn_comentar: "Contactez-nous",
        cat_desc_serv: "Attention personnalisée et spécialisée.",
        cat_btn_main: "CATALOGUE DE MODÈLES ET SERVICES", 
        cat_modal_title: "CATALOGUE COMMERCIAL", 
        cat_modal_subtitle: "Sélectionnez la section de votre intérêt", 
        cat_btn_autos: "CATALOGUE DE VOITURES", 
        cat_btn_servicios: "SERVICES PERSONNALISÉS",
        cat_btn_interes: "Ça m'intéresse",
        cat_btn_comentar: "Contactez-nous",
        cat_desc_serv: "Attention personnalisée et spécialisée."
    },
    ko: {
        titulo_app: "SIPVEC - 상업 지능 시스템",
        bienvenida: "환영합니다",
        menu_quienes: "회사 소개",
        menu_excelencia: "우수성",
        menu_asistente: "빠른 지원 및 문의",
        menu_redes: "WhatsApp 및 소셜 미디어",
        btn_evolucion: "동영상 / 우리와 함께 진화를 경험하세요",
        btn_asesor: "전문 상담원 선택 / 지도!",
        btn_cuestionario: "설문지 시작",
        btn_valoracion: "상담원의 응대를 평가해주세요",
        btn_finalizar: "완료 및 전송",
        btn_compartir_experiencia: "제니스 카(ZENITH CAR)에서 구매했습니다. 최고의 경험이네요! 공유해 드립니다.",
        footer_producido: "\"PIDE YA\" CARD 제작",
        modal_evolucion_titulo: "진화를 경험하세요",
        modal_evolucion_subtitulo: "우리가 다른 이유를 확인하세요",
        btn_lujo: "당신이 누릴 가치가 있는 럭셔리",
        btn_tecnologia: "기술 및 혁신",
        btn_momento: "지금이 당신의 순간입니다",
        btn_asistencia: "전문 지원",
        faq_titulo: "자주 묻는 질문",
        faq_q1: "차량 구매 또는 렌트 시 무엇이 포함되나요?",
        faq_r1: "모든 차량에는 대리점 보증, 주유소 만땅 서비스, 도로 안전 키트 및 출고 전 철저한 디테일링 작업이 포함되어 있습니다.",
        faq_q2: "시설이나 인도 장소는 어디에 있나요?",
        faq_r2: "메인 쇼룸과 출고 구역은 메인 쇼룸에 위치해 있습니다. 예약 시 상세한 안내가 WhatsApp으로 전송됩니다.",
        faq_q3: "계약금 취소 또는 환불 정책은 어떻게 되나요?",
        faq_r3: "신용 심사 취소 시 또는 계약 체결 최소 48시간 전에 요청하는 경우 전액 환불이 적용됩니다.",
        faq_q4: "차량을 예약하거나 할부 금융을 이용하려면 어떻게 해야 하나요?",
        faq_r4: "카드 또는 계좌 이체를 통해 초기 예치금으로 차량을 확보할 수 있으며, 차량 인도 시 잔금을 치르거나 금융 플랜을 시작할 수 있습니다.",
        faq_q5: "시승(Test Drive) 옵션을 제공하나요?",
        faq_r5: "물론입니다! 사전 예약 및 유효한 운전면허증 소지자를 대상으로 전 모델 시승이 가능합니다.",
        contact_titulo: "연락처",
        contact_sub: "공식 채널과 소셜 미디어를 팔로우하세요!",
        btn_wsp: "WhatsApp 채팅",
        btn_web: "공식 웹사이트",
        btn_fb: "공식 페이스북",
        btn_ig: "인스타그램",
        qr_titulo: "QR 코드 스캔",
        btn_qr: "QR 공유",
        cat1_t: "회사 소개",
        cat1_c: "ZENITH CAR는 고도의 엔지니어링, 순수한 스포티함, 최첨단 안전성, 일상적인 운전 경험을 진정한 드라이빙의 즐거움으로 끌어올리는 세련된 디자인을 제공하여 지역 내 프리미엄 모빌리티를 재정의합니다.",
        cat2_t: "우수성",
        cat2_c: "당사의 프리미엄 자동차 서비스를 살펴보세요: ZENITH CAR 신차 판매, 맞춤형 및 기업형 금융 플랜, 맞춤형 시승, 고도로 전문화된 정비 공장 및 정품 부품 판매.",
        cat3_t: "만족한 고객",
        cat3_c: "당사의 최우선 과제는 서비스 우수성입니다. 아과스칼리엔테스의 운전자와 가족들은 ZENITH CAR의 선진 엔지니어링과 스포티함만이 제공할 수 있는 품질, 편안함, 뛰어난 성능을 보증합니다.",
        header_asistente_titulo: "맞춤형 어시스턴트",
        header_asistente_bienvenida: "환영합니다! 고객님께 딱 맞는 전문가를 찾도록 도와드리겠습니다. 간단한 질문에 몇 초만 답해 주세요.",
        paso1_titulo: "1단계. 잠재 고객 기본 정보",
        paso1_desc: "이 정보는 신속한 후속 조치를 위해 사용됩니다.",
        label_nombre: "전체 이름 *",
        label_whatsapp: "WhatsApp *",
        label_correo: "이메일 (선택 사항)",
        label_contacto: "어떤 방식으로 연락을 원하시나요?",
        btn_wsp_contacto: "WhatsApp",
        btn_llamada: "전화",
        btn_correo_contacto: "이메일",
        btn_regresar: "메뉴로 돌아가기",
        resena_titulo: "서비스 평가 (기밀)",
        resena_desc: "담당 상담원을 선택하여 영업 관리부로 직접 평가를 보내주세요.",
        paso2_titulo: "2단계. 어떤 차량에 관심이 있으신가요?",
        paso2_desc: "시장서 가장 관심도가 높은 모델을 상담원에게 알려주세요.",
        btn_modelo_sedan: "세단 / 콤팩트",
        btn_modelo_suv: "SUV / 소형 SUV",
        btn_modelo_deportivo: "스포츠 / 고성능",
        btn_modelo_pickup: "픽업트럭",
        btn_modelo_hibrido: "하이브리드 / 전기차",
        btn_modelo_nose: "아직 잘 모르겠습니다",
        paso3_titulo: "3단계. 어떤 종류의 차량을 찾고 계시나요?",
        paso3_desc: "자동차 실루엣의 초기 프로파일링.",
        btn_tipo_suv: "SUV",
        btn_tipo_sedan: "세단",
        btn_tipo_deportivo: "스포츠",
        btn_tipo_electrico: "전기차",
        btn_tipo_hibrido: "하이브리드",
        btn_tipo_familiar: "패밀리",
        btn_tipo_ejecutivo: "이그제큐티브",
        btn_tipo_otro: "기타",
        paso4_titulo: "4단계. 주로 어떤 용도로 사용하시겠습니까?",
        paso4_desc: "상업적 기술 효용성에 따른 세분화.",
        btn_uso_personal: "개인용",
        btn_uso_familiar: "패밀리용",
        btn_uso_empresa: "기업용",
        btn_uso_uber: "우버 / 디디 이그제큐티브",
        btn_uso_viajes: "여행용",
        btn_uso_trabajo: "업무용",
        btn_uso_otro: "기타",
        paso5_titulo: "5단계. 언제 구매할 계획이십니까?",
        paso5_desc: "이 긴급성 지표는 경영진에게 매우 중요합니다.",
        btn_tiempo_semana: "이번 주",
        btn_tiempo_mes: "이번 달",
        btn_tiempo_3meses: "3개월 이내",
        btn_tiempo_6meses: "6개월 이내",
        btn_tiempo_investigando: "정보 수집 중",
        btn_anterior: "이전",
        btn_siguiente: "다음",
        paso6_titulo: "6단계. 어떻게 구매할 계획이십니까?",
        paso6_desc: "금융 방식 프로파일링.",
        btn_metodo_contado: "현금 일시불",
        btn_metodo_credito: "할부 금융",
        btn_metodo_arrendamiento: "리스(임대)",
        btn_metodo_nose: "아직 잘 모르겠습니다",
        paso7_titulo: "7단계. 예상 예산은 어느 정도이신가요?",
        paso7_desc: "구매력 분류.",
        paso8_titulo: "8단계. 가장 눈길이 갔던 프로모션은 무엇인가요?",
        paso8_desc: "진행 중인 캠페인의 효과를 직접적으로 측정합니다.",
        btn_promo_verano: "썸머 보너스",
        btn_promo_tasa: "금리 8.99%",
        btn_promo_seguro: "무료 보험",
        btn_promo_mantenimiento: "유지보수 포함",
        btn_promo_test: "시승 (Test Drive)",
        btn_promo_otro: "기타",
        paso9_titulo: "9단계. 저희 에이전시를 어떻게 알게 되셨나요?",
        paso9_desc: "광고 투자 수익률(ROI)에 대한 순수 감사.",
        btn_origen_asesor: "담당 상담원",
        btn_origen_amigo: "지인 추천",
        btn_origen_fb: "페이스북",
        btn_origen_ig: "인스타그램",
        btn_origen_wa: "왓츠앱",
        btn_origen_google: "구글",
        btn_origen_web: "웹사이트",
        btn_origen_qr: "QR 코드",
        btn_origen_otro: "기타",
        paso10_titulo: "10단계. 추천 상담원",
        paso10_desc: "제공해주신 정보를 바탕으로 추천드리는 상담원입니다. 탭을 클릭하세요:",
        paso10_cambiar: "원하시는 경우 여기서 변경하실 수 있습니다:",
        btn_finalizar: "완료 및 전송",
        titulo_asesor_digital: "디지털 상담원에게 연락하기",
        desc_asesor_digital: "즉각적인 지원을 위해 선호하는 상담원을 선택하세요 / 이름을 클릭하세요.",
        btn_como_llegar: "오시는 길",
        btn_cerrar: "닫기",
        footer_producido: "제작:",
        gerente_titulo_principal: "자동차 대리점 - 감사 제어",
        btn_salir: "나가기",
        gerente_html_title: "관리 패널 - 대행사 리드 제어",
        gerente_login_titulo: "상업 총괄",
        gerente_login_desc: "관리자 감사 키를 입력하세요",
        gerente_placeholder_clave: "액세스 키...",
        gerente_btn_ingresar: "패널 입장",
        gerente_titulo_principal: "자동차 대리점 - 감사 제어",
        btn_salir: "나가기",
        gerente_html_title: "관리 패널 - 대행사 리드 제어",
        gerente_login_titulo: "상업 총괄",
        gerente_login_desc: "관리자 감사 키를 입력하세요",
        gerente_placeholder_clave: "액세스 키...",
        gerente_btn_ingresar: "패널 입장",
        gerente_titulo_principal: "자동차 대리점 - 감사 제어",
        btn_salir: "나가기",
        gerente_kpi_total: "전체 리드",
        gerente_kpi_verde: "즉시 진행 (녹색)",
        gerente_kpi_amarillo: "팔로업 중 (노란색)",
        gerente_kpi_rojo: "조건 대기 (빨간색)",
        gerente_seccion_estatus: "고객 성숙도 상태",
        gerente_html_title: "관리 패널 - 대행사 리드 제어",
        gerente_login_titulo: "상업 총괄",
        gerente_login_desc: "관리자 감사 키를 입력하세요",
        gerente_placeholder_clave: "액세스 키...",
        gerente_btn_ingresar: "패널 입장",
        gerente_titulo_principal: "자동차 대리점 - 감사 제어",
        btn_salir: "나가기",
        gerente_kpi_total: "전체 리드",
        gerente_kpi_verde: "즉시 진행 (녹색)",
        gerente_kpi_amarillo: "팔로업 중 (노란색)",
        gerente_kpi_rojo: "조건 대기 (빨간색)",
        gerente_seccion_estatus: "고객 성숙도 상태",
        gerente_btn_excel: "엑셀 다운로드 (CSV)",
        gerente_btn_limpiar: "패널 지우기",
        gerente_th_estado: "상태",
        gerente_th_cliente: "고객 / 잠재고객",
        gerente_th_contacto: "전화번호 / 연락처",
        gerente_th_asesor: "배정된 상담원",
        gerente_th_fecha: "첫 연락 / 날짜",
        gerente_th_intentos: "팔로업 시도 횟수",
        gerente_html_title: "관리 패널 - 대행사 리드 제어",
        gerente_login_titulo: "상업 총괄",
        gerente_login_desc: "관리자 감사 키를 입력하세요",
        gerente_placeholder_clave: "액세스 키...",
        gerente_btn_ingresar: "패널 입장",
        gerente_titulo_principal: "자동차 대리점 - 감사 제어",
        btn_salir: "나가기",
        gerente_kpi_total: "전체 리드",
        gerente_kpi_verde: "즉시 진행 (녹색)",
        gerente_kpi_amarillo: "팔로업 중 (노란색)",
        gerente_kpi_rojo: "조건 대기 (빨간색)",
        gerente_seccion_estatus: "고객 성숙도 상태",
        gerente_btn_excel: "엑셀 다운로드 (CSV)",
        gerente_btn_limpiar: "패널 지우기",
        gerente_th_estado: "상태",
        gerente_th_cliente: "고객 / 잠재고객",
        gerente_th_contacto: "전화번호 / 연락처",
        gerente_th_asesor: "배정된 상담원",
        gerente_th_fecha: "첫 연락 / 날짜",
        gerente_th_intentos: "팔로업 시도 횟수",
        gerente_seccion_record: "상담원별 링크 전송 기록",
        gerente_th_asesor_nombre: "상담원",
        gerente_th_total_envios: "총 전송 / 공유 횟수",
        gerente_seccion_reseñas: "상담원 기밀 평가 및 리뷰",
        gerente_th_fecha_res: "날짜",
        gerente_th_asesor_eval: "평가된 상담원",
        gerente_th_calificacion: "평점",
        gerente_th_comentario: "고객 코멘트",
        alerta_calificacion_exito: "관리 패널에 평점이 성공적으로 저장되었습니다!",
    alerta_vaciar_panel: "감사 패널을 완전히 비우시겠습니까?",
    alerta_excel_vacio: "내보낼 리드 기록이 없습니다.",
    gerente_texto_envios: "전송",
    gerente_texto_veces: "회",
    status_green: "판매 진행",
    status_yellow: "팔로우업 및 알림",
    status_red: "완전 정지 / 조사 중",
    cat_btn_main: "모델 및 서비스 카탈로그", 
        cat_modal_title: "상업용 카탈로그", 
        cat_modal_subtitle: "관심 있는 섹션을 선택하세요", 
        cat_btn_autos: "자동차 카탈로그", 
        cat_btn_servicios: "맞춤형 서비스",
        cat_btn_interes: "관심 있습니다",
        cat_btn_comentar: "문의하기",
        cat_desc_serv: "맞춤형 전문 상담.",
        cat_btn_main: "모델 및 서비스 카탈로그", 
        cat_modal_title: "상업용 카탈로그", 
        cat_modal_subtitle: "관심 있는 섹션을 선택하세요", 
        cat_btn_autos: "자동차 카탈로그", 
        cat_btn_servicios: "맞춤형 서비스",
        cat_btn_interes: "관심 있습니다",
        cat_btn_comentar: "문의하기",
        cat_desc_serv: "맞춤형 전문 상담."
    
    },
    ja: {
        titulo_app: "SIPVEC - 商用インテリジェンスシステム",
        bienvenida: "ようこそ",
        menu_quienes: "私たちについて",
        menu_excelencia: "卓越性",
        menu_asistente: "クイックアシスタントとFAQ",
        menu_redes: "WhatsApp & ソーシャルメディア",
        btn_evolucion: "動画 / 私たちと一緒に進化を体験しましょう",
        btn_asesor: "専門アドバイザーを選択 / マップ！",
        btn_cuestionario: "アンケートを開始する",
        btn_valoracion: "担当アドバイザーの対応を評価する",
        btn_finalizar: "完了して送信",
        btn_compartir_experiencia: "ZENITH CARで購入しました。素晴らしい体験でした！シェアします。",
        footer_producido: "制作: \"PIDE YA\" CARD",
        modal_evolucion_titulo: "進化を体験する",
        modal_evolucion_subtitulo: "私たちが選ばれる理由",
        btn_lujo: "あなたにふさわしい贅沢",
        btn_tecnologia: "技術と革新",
        btn_momento: "今がその時です",
        btn_asistencia: "専門的なサポート",
        faq_titulo: "よくある質問",
        faq_q1: "車両の購入またはレンタルには何が含まれますか？",
        faq_r1: "すべての車両にメーカー保証、満タンのガソリン、ロードセーフティキット、納車前の徹底したディテーリングが含まれています。",
        faq_q2: "施設や納車場所はどこにありますか？",
        faq_r2: "メインショールームと納車エリアはメインショールーム内にあります。ご予約時に詳細なご案内がWhatsAppで送信されます。",
        faq_q3: "キャンセルや手付金の返金ポリシーはどうなっていますか？",
        faq_r3: "クレジット審査がキャンセルされた場合、または契約締結の48時間前までにキャンセルが申請された場合、全額返金が適用されます。",
        faq_q4: "車の予約やファイナンシングの方法を教えてください。",
        faq_r4: "カードまたは銀行振込による初期預かり金で車両を確保し、納車時に残金の決済またはファイナンシャルプランを開始できます。",
        faq_q5: "試乗（テストドライブ）はできますか？",
        faq_r5: "もちろん可能です！現在展開中のすべてのモデルで、事前予約および有効な運転免許証のご提示により試乗が可能です。",
        contact_titulo: "お問い合わせ",
        contact_sub: "公式SNSやチャンネルをぜひフォローしてください！",
        btn_wsp: "WhatsAppチャット",
        btn_web: "公式サイト",
        btn_fb: "公式Facebook",
        btn_ig: "Instagram",
        qr_titulo: "QRコードをスキャン",
        btn_qr: "QRをシェア",
        cat1_t: "私たちについて",
        cat1_c: "ZENITH CARは、高度なエンジニアリング、純粋なスポーティネス、最先端の安全性、そして毎日のドライブ体験を真の歓びへと昇華させる洗練されたデザインを提供し、地域におけるプレミアムモビリティを再定義します。",
        cat2_t: "卓越性",
        cat2_c: "当社のプレミアム自動車サービスをご覧ください：ZENITH CAR新型車の販売、お客様のニーズに合わせた法人・個別ファイナンスプラン、パーソナライズされた試乗体験、高度な専門メカニカルワークショップ、純正パーツの販売。",
        cat3_t: "お客様の声",
        cat3_c: "私たちの最優先事項はサービスの卓越性です。アグアスカリエンテスのドライバーやご家族は、ZENITH CARの先進エンジニアリングとスポーティネスだけが提供できる品質、快適性、そして卓越したパフォーマンスを支持しています。",
        header_asistente_titulo: "パーソナライズアシスタント",
        header_asistente_bienvenida: "ようこそ！あなたにぴったりの専門家を見つけるお手伝いをします。いくつかの簡単な質問に答えるだけです。",
        paso1_titulo: "ステップ1. 見込み顧客の基本データ",
        paso1_desc: "迅速なフォローアップのための情報です。",
        label_nombre: "氏名 *",
        label_whatsapp: "WhatsApp *",
        label_correo: "メールアドレス (任意)",
        label_contacto: "希望する連絡方法は？",
        btn_wsp_contacto: "WhatsApp",
        btn_llamada: "電話",
        btn_correo_contacto: "メール",
        btn_regresar: "メニューに戻る",
        resena_titulo: "サービス評価（機密）",
        resena_desc: "担当アドバイザーを選択し、営業管理部へ直接評価を送信してください。",
        paso2_titulo: "ステップ2. どの車両に興味がありますか？",
        paso2_desc: "市場で関心を集めているモデルをアドバイザーにお知らせください。",
        btn_modelo_sedan: "セダン / コンパクト",
        btn_modelo_suv: "SUV / クロスオーバー",
        btn_modelo_deportivo: "スポーツ / ハイパフォーマンス",
        btn_modelo_pickup: "ピックアップ",
        btn_modelo_hibrido: "ハイブリッド / 電気自動車",
        btn_modelo_nose: "まだ決めていない",
        paso3_titulo: "ステップ3. どのようなタイプの車両をお探しですか？",
        paso3_desc: "自動車のシルエットの初期プロファイリング。",
        btn_tipo_suv: "SUV",
        btn_tipo_sedan: "セダン",
        btn_tipo_deportivo: "スポーツ",
        btn_tipo_electrico: "電気自動車",
        btn_tipo_hibrido: "ハイブリッド",
        btn_tipo_familiar: "ファミリー",
        btn_tipo_ejecutivo: "エグゼクティブ",
        btn_tipo_otro: "その他",
        paso4_titulo: "ステップ4. 主にどのような目的で使用しますか？",
        paso4_desc: "商業的有用性に基づくセグメンテーション。",
        btn_uso_personal: "個人利用",
        btn_uso_familiar: "ファミリー利用",
        btn_uso_empresa: "企業利用",
        btn_uso_uber: "Uber / Didi エグゼクティブ",
        btn_uso_viajes: "旅行",
        btn_uso_trabajo: "仕事",
        btn_uso_otro: "その他",
        paso5_titulo: "ステップ5. 購入予定はいつですか？",
        paso5_desc: "この緊急度の指標は経営陣にとって極めて重要です。",
        btn_tiempo_semana: "今週",
        btn_tiempo_mes: "今月",
        btn_tiempo_3meses: "3ヶ月以内",
        btn_tiempo_6meses: "6ヶ月以内",
        btn_tiempo_investigando: "情報収集のみ",
        btn_anterior: "前へ",
        btn_siguiente: "次へ",
        paso6_titulo: "ステップ6. どのような方法で購入しますか？",
        paso6_desc: "金融スキームのプロファイリング。",
        btn_metodo_contado: "現金一括",
        btn_metodo_credito: "クレジット（ローン）",
        btn_metodo_arrendamiento: "リース",
        btn_metodo_nose: "まだ決めていない",
        paso7_titulo: "ステップ7. おおよその予算はいくらですか？",
        paso7_desc: "購買力の分類。",
        paso8_titulo: "ステップ8. 最も気になったプロモーションは何ですか？",
        paso8_desc: "アクティブなキャンペーンの効果を直接測定します。",
        btn_promo_verano: "サマーボーナス",
        btn_promo_tasa: "金利 8.99%",
        btn_promo_seguro: "無料保険",
        btn_promo_mantenimiento: "メンテナンス込み",
        btn_promo_test: "試乗（テストドライブ）",
        btn_promo_otro: "その他",
        paso9_titulo: "ステップ9. 当エージェンシーを何でお知りになりましたか？",
        paso9_desc: "広告に対する投資収益率（ROI）の純粋な監査。",
        btn_origen_asesor: "担当アドバイザー",
        btn_origen_amigo: "友人",
        btn_origen_fb: "Facebook",
        btn_origen_ig: "Instagram",
        btn_origen_wa: "WhatsApp",
        btn_origen_google: "Google",
        btn_origen_web: "ウェブサイト",
        btn_origen_qr: "QRコード",
        btn_origen_otro: "その他",
        paso10_titulo: "ステップ10. 推奨アドバイザー",
        paso10_desc: "ご提供いただいた情報に基づき、推奨アドバイザーをご提案します。タブをクリックしてください：",
        paso10_cambiar: "ご希望であれば、こちらから変更可能です：",
        btn_finalizar: "完了して送信",
        titulo_asesor_digital: "デジタルアドバイザーに連絡する",
        desc_asesor_digital: "迅速な対応をご希望のアドバイザーをお選びください / お名前をクリックしてください。",
        btn_como_llegar: "アクセス",
        btn_cerrar: "閉じる",
        footer_producido: "制作:",
        gerente_titulo_principal: "自動車ディーラー - 監査コントロール",
        btn_salir: "ログアウト",
        gerente_html_title: "管理パネル - 代理店リードコントロール",
        gerente_login_titulo: "商業統括",
        gerente_login_desc: "管理監査キーを入力してください",
        gerente_placeholder_clave: "アクセスキー...",
        gerente_btn_ingresar: "パネルに入る",
        gerente_titulo_principal: "自動車ディーラー - 監査コントロール",
        btn_salir: "ログアウト",
        gerente_html_title: "管理パネル - 代理店リードコントロール",
        gerente_login_titulo: "商業統括",
        gerente_login_desc: "管理監査キーを入力してください",
        gerente_placeholder_clave: "アクセスキー...",
        gerente_btn_ingresar: "パネルに入る",
        gerente_titulo_principal: "自動車ディーラー - 監査コントロール",
        btn_salir: "ログアウト",
        gerente_kpi_total: "総リード数",
        gerente_kpi_verde: "今すぐ進める (緑)",
        gerente_kpi_amarillo: "追跡中 (黄)",
        gerente_kpi_rojo: "条件待ち (赤)",
        gerente_seccion_estatus: "顧客の成熟ステータス",
        gerente_html_title: "管理パネル - 代理店リードコントロール",
        gerente_login_titulo: "商業統括",
        gerente_login_desc: "管理監査キーを入力してください",
        gerente_placeholder_clave: "アクセスキー...",
        gerente_btn_ingresar: "パネルに入る",
        gerente_titulo_principal: "自動車ディーラー - 監査コントロール",
        btn_salir: "ログアウト",
        gerente_kpi_total: "総リード数",
        gerente_kpi_verde: "今すぐ進める (緑)",
        gerente_kpi_amarillo: "追跡中 (黄)",
        gerente_kpi_rojo: "条件待ち (赤)",
        gerente_seccion_estatus: "顧客の成熟ステータス",
        gerente_btn_excel: "Excel (CSV) をダウンロード",
        gerente_btn_limpiar: "パネルをクリア",
        gerente_th_estado: "ステータス",
        gerente_th_cliente: "顧客 / 見込み客",
        gerente_th_contacto: "電話番号 / 連絡先",
        gerente_th_asesor: "担当アドバイザー",
        gerente_th_fecha: "初回接触 / 日付",
        gerente_th_intentos: "追跡試行回数",
        gerente_html_title: "管理パネル - 代理店リードコントロール",
        gerente_login_titulo: "商業統括",
        gerente_login_desc: "管理監査キーを入力してください",
        gerente_placeholder_clave: "アクセスキー...",
        gerente_btn_ingresar: "パネルに入る",
        gerente_titulo_principal: "自動車ディーラー - 監査コントロール",
        btn_salir: "ログアウト",
        gerente_kpi_total: "総リード数",
        gerente_kpi_verde: "今すぐ進める (緑)",
        gerente_kpi_amarillo: "追跡中 (黄)",
        gerente_kpi_rojo: "条件待ち (赤)",
        gerente_seccion_estatus: "顧客の成熟ステータス",
        gerente_btn_excel: "Excel (CSV) をダウンロード",
        gerente_btn_limpiar: "パネルをクリア",
        gerente_th_estado: "ステータス",
        gerente_th_cliente: "顧客 / 見込み客",
        gerente_th_contacto: "電話番号 / 連絡先",
        gerente_th_asesor: "担当アドバイザー",
        gerente_th_fecha: "初回接触 / 日付",
        gerente_th_intentos: "追跡試行回数",
        gerente_seccion_record: "アドバイザー別リンク送信記録",
        gerente_th_asesor_nombre: "アドバイザー",
        gerente_th_total_envios: "総送信 / 共有数",
        gerente_seccion_reseñas: "機密評価とアドバイザーレビュー",
        gerente_th_fecha_res: "日付",
        gerente_th_asesor_eval: "評価されたアドバイザー",
        gerente_th_calificacion: "評価",
        gerente_th_comentario: "顧客のコメント",
        alerta_calificacion_exito: "管理パネルの評価が正常に保存されました！",
    alerta_vaciar_panel: "監査パネルを完全にクリアしてもよろしいですか？",
    alerta_excel_vacio: "エクスポートするリードの記録がありません。",
    gerente_texto_envios: "送信",
    gerente_texto_veces: "回",
    status_green: "販売を進める",
    status_yellow: "フォローアップとアラート",
    status_red: "完全停止 / 調査中",
    cat_btn_main: "モデルとサービスカタログ", 
        cat_modal_title: "商業カタログ", 
        cat_modal_subtitle: "興味のあるセクションを選択してください", 
        cat_btn_autos: "自動車カタログ", 
        cat_btn_servicios: "カスタマイズされたサービス",
        cat_btn_interes: "興味があります",
        cat_btn_comentar: "お問い合わせ",
        cat_desc_serv: "パーソナライズされた専門的な対応。",
        cat_btn_main: "モデルとサービスカタログ", 
        cat_modal_title: "商業カタログ", 
        cat_modal_subtitle: "興味のあるセクションを選択してください", 
        cat_btn_autos: "自動車カタログ", 
        cat_btn_servicios: "カスタマイズされたサービス",
        cat_btn_interes: "興味があります",
        cat_btn_comentar: "お問い合わせ",
        cat_desc_serv: "パーソナライズされた専門的な対応。"
    },
    de: {
        titulo_app: "SIPVEC - Kommerzielles Intelligenzsystem",
        bienvenida: "WILLKOMMEN",
        menu_quienes: "ÜBER UNS",
        menu_excelencia: "EXZELLENZ",
        menu_asistente: "SCHNELLER ASSISTENT & FAQ",
        menu_redes: "WHATSAPP & SOZIALE MEDIEN",
        btn_evolucion: "VIDEOS / ERLEBEN SIE DIE EVOLUTION MIT UNS",
        btn_asesor: "WÄHLEN SIE IHREN SPEZIALISIERTEN BERATER / MAPS!",
        btn_cuestionario: "Fragebogen starten",
        btn_valoracion: "BEWERTEN SIE DEN SERVICE IHRES BERATERS",
        btn_finalizar: "ABSCHLIESSEN UND SENDEN",
        btn_compartir_experiencia: "Ich habe bei ZENITH CAR gekauft. Exzellente Erfahrung! Ich teile sie mit Ihnen.",
        footer_producido: "PRODUZIERT VON \"PIDE YA\" CARD",
        modal_evolucion_titulo: "ERLEBEN SIE DIE EVOLUTION",
        modal_evolucion_subtitulo: "Entdecken Sie, was uns anders macht",
        btn_lujo: "DER LUXUS, DEN SIE VERDIENEN",
        btn_tecnologia: "TECHNOLOGIE UND INNOVATION",
        btn_momento: "DAS IST IHR MOMENT",
        btn_asistencia: "SPEZIALISIERTE UNTERSTÜTZUNG",
        faq_titulo: "HÄUFIG GESTELLTE FRAGEN",
        faq_q1: "Was ist beim Kauf oder der Miete eines Fahrzeugs inbegriffen?",
        faq_r1: "Alle unsere Fahrzeuge beinhalten eine Werksgarantie, eine kostenlose Tankfüllung, ein Pannenschutzset und eine sorgfältige Aufbereitung vor der Übergabe.",
        faq_q2: "Wo befinden sich die Einrichtungen oder der Übergabepunkt?",
        faq_r2: "Unser Hauptshowroom und Übergabebereich befinden sich im Hauptshowroom. Detaillierte Anweisungen werden bei der Terminvereinbarung per WhatsApp gesendet.",
        faq_q3: "Wie lautet die Stornierungs- oder Anzahlungs-Rückgabepolitik?",
        faq_r3: "Volle Rückerstattungen erfolgen im Falle einer Kreditablehnung oder wenn die Stornierung mindestens 48 Stunden vor Vertragsunterzeichnung beantragt wird.",
        faq_q4: "Wie kann ich ein Auto reservieren oder finanzieren?",
        faq_r4: "Sie können Ihr Fahrzeug mit einer Anzahlung per Karte oder Banküberweisung sichern und den Restbetrag oder Finanzierungsplan zum Zeitpunkt der Übergabe abwickeln.",
        faq_q5: "Bieten Sie Probefahrten (Test Drive) an?",
        faq_r5: "Natürlich! Wir bieten für alle aktuellen Modelle Probefahrten nach vorheriger Terminvereinbarung und mit gültigem Führerschein an.",
        contact_titulo: "KONTAKT",
        contact_sub: "Folgen Sie uns auf unseren offiziellen Netzwerken und Kanälen!",
        btn_wsp: "WHATSAPP-CHAT",
        btn_web: "OFFIZIELLE WEBSITE",
        btn_fb: "OFFIZIELLES FACEBOOK",
        btn_ig: "INSTAGRAM",
        qr_titulo: "QR-CODE SCANNEN",
        btn_qr: "QR TEILEN",
        cat1_t: "ÜBER UNS",
        cat1_c: "ZENITH CAR definiert die Premium-Mobilität in der Region neu und bietet Fahrzeuge mit Hochtechnologie, purer Sportlichkeit, modernster Sicherheit und einem raffinierten Design, das das tägliche Fahrerlebnis in ein wahres Fahrvergnügen verwandelt.",
        cat2_t: "EXZELLENZ",
        cat2_c: "Entdecken Sie unser Angebot an Premium-Automobildienstleistungen: Verkauf von Neufahrzeugen der Linie ZENITH CAR, maßgeschneiderte und Firmenfinanzierungspläne, personalisierte Probefahrten, hochspezialisierte Werkstatt und Verkauf von Originalersatzteilen.",
        cat3_t: "GLÜCKLICHE KUNDEN",
        cat3_c: "Unsere Priorität ist herausragender Service. Fahrer und Familien in Aguascalientes unterstützen die Qualität, das Komfort und die außergewöhnliche Leistung, die nur die fortgeschrittene Ingenieurskunst und Sportlichkeit von ZENITH CAR bieten können.",
        header_asistente_titulo: "Personalisierter Assistent",
        header_asistente_bienvenida: "Willkommen! Wir helfen Ihnen gerne dabei, den idealen Spezialisten für Sie zu finden. Es dauert nur wenige Sekunden, um ein paar kurze Fragen zu beantworten.",
        paso1_titulo: "SCHRITT 1. Basisdaten des Interessenten",
        paso1_desc: "Diese Daten ermöglichen eine zeitnahe Nachverfolgung.",
        label_nombre: "Vollständiger Name *",
        label_whatsapp: "WhatsApp *",
        label_correo: "E-Mail (optional)",
        label_contacto: "Wie möchten Sie kontaktiert werden?",
        btn_wsp_contacto: "WhatsApp",
        btn_llamada: "Anruf",
        btn_correo_contacto: "E-Mail",
        btn_regresar: "Zurück zum Menú",
        resena_titulo: "Servicebewertung (Vertraulich)",
        resena_desc: "Wählen Sie Ihren Berater aus, um Ihre Bewertung direkt an die Verkaufsleitung zu senden.",
        paso2_titulo: "SCHRITT 2. Welches Fahrzeug interessiert Sie?",
        paso2_desc: "Informieren Sie den Berater, welche Modelle das meiste Marktinteresse generieren.",
        btn_modelo_sedan: "Sedan / Kompaktwagen",
        btn_modelo_suv: "SUV / Geländewagen",
        btn_modelo_deportivo: "Sportwagen",
        btn_modelo_pickup: "Pick-up",
        btn_modelo_hibrido: "Hybrid / Elektro",
        btn_modelo_nose: "Weiß noch nicht",
        paso3_titulo: "SCHRITT 3. Welche Fahrzeugart suchen Sie?",
        paso3_desc: "Erstes Profiling der Fahrzeugsilhouette.",
        btn_tipo_suv: "SUV",
        btn_tipo_sedan: "Limousine",
        btn_tipo_deportivo: "Sportwagen",
        btn_tipo_electrico: "Elektro",
        btn_tipo_hibrido: "Hybrid",
        btn_tipo_familiar: "Familienfahrzeug",
        btn_tipo_ejecutivo: "Executive",
        btn_tipo_otro: "Andere",
        paso4_titulo: "SCHRITT 4. Wofür werden Sie es hauptsächlich nutzen?",
        paso4_desc: "Segmentierung der kommerziellen technischen Nutzung.",
        btn_uso_personal: "Persönliche Nutzung",
        btn_uso_familiar: "Familiennutzung",
        btn_uso_empresa: "Unternehmen",
        btn_uso_uber: "Uber / Didi Exec",
        btn_uso_viajes: "Reisen",
        btn_uso_trabajo: "Arbeit",
        btn_uso_otro: "Andere",
        paso5_titulo: "SCHRITT 5. Wann planen Sie zu kaufen?",
        paso5_desc: "Diese Dringlichkeitsmetrik ist Gold wert für das Management.",
        btn_tiempo_semana: "Diese Woche",
        btn_tiempo_mes: "Diesen Monat",
        btn_tiempo_3meses: "Innerhalb von 3 Monaten",
        btn_tiempo_6meses: "Innerhalb von 6 Monaten",
        btn_tiempo_investigando: "Recherchiere nur",
        btn_anterior: "Zurück",
        btn_siguiente: "Weiter",
        paso6_titulo: "SCHRITT 6. Wie planen Sie den Erwerb?",
        paso6_desc: "Profilierung des Finanzierungsschemas.",
        btn_metodo_contado: "Barzahlung",
        btn_metodo_credito: "Kredit",
        btn_metodo_arrendamiento: "Leasing",
        btn_metodo_nose: "Weiß noch nicht",
        paso7_titulo: "SCHRITT 7. Wie hoch ist Ihr ungefähres Budget?",
        paso7_desc: "Klassifizierung der Kaufkraft.",
        paso8_titulo: "SCHRITT 8. Welche Aktion hat Ihre Aufmerksamkeit am meisten erregt?",
        paso8_desc: "Misst direkt die Wirksamkeit aktiver Kampagnen.",
        btn_promo_verano: "Sommerbonus",
        btn_promo_tasa: "8,99% Zinssatz",
        btn_promo_seguro: "Kostenlose Versicherung",
        btn_promo_mantenimiento: "Wartung inklusive",
        btn_promo_test: "Probefahrt (Test Drive)",
        btn_promo_otro: "Anderes",
        paso9_titulo: "SCHRITT 9. Wie haben Sie von unserer AGENTUR erfahren?",
        paso9_desc: "Reines ROI-Audit für Werbung.",
        btn_origen_asesor: "Mein Berater",
        btn_origen_amigo: "Ein Freund",
        btn_origen_fb: "Facebook",
        btn_origen_ig: "Instagram",
        btn_origen_wa: "WhatsApp",
        btn_origen_google: "Google",
        btn_origen_web: "Webseite",
        btn_origen_qr: "QR-Code",
        btn_origen_otro: "Anderes",
        paso10_titulo: "SCHRITT 10. Empfohlener Berater",
        paso10_desc: "Basierend auf Ihren Angaben empfehlen wir diesen Berater. Klicken Sie auf seine Registerkarte:",
        paso10_cambiar: "Falls Sie jedoch einen anderen bevorzugen, können Sie diesen hier ändern:",
        btn_finalizar: "ABSCHLIESSEN UND SENDEN",
        titulo_asesor_digital: "Kontaktieren Sie Ihren digitalen Berater",
        desc_asesor_digital: "Wählen Sie Ihren bevorzugten Berater für sofortige Betreuung / Klicken Sie auf seinen Namen.",
        btn_como_llegar: "ANFAHRT",
        btn_cerrar: "Schließen",
        footer_producido: "PRODUZIERT VON",
        gerente_titulo_principal: "Autohaus - Audit-Kontrolle",
        btn_salir: "Abmelden",
        gerente_html_title: "Management-Panel - Agentur-Lead-Steuerung",
        gerente_login_titulo: "Handelsleitung",
        gerente_login_desc: "Geben Sie den Management-Audit-Schlüssel ein",
        gerente_placeholder_clave: "Zugriffsschlüssel...",
        gerente_btn_ingresar: "Panel betreten",
        gerente_titulo_principal: "Autohaus - Audit-Kontrolle",
        btn_salir: "Abmelden",
        gerente_html_title: "Management-Panel - Agentur-Lead-Steuerung",
        gerente_login_titulo: "Handelsleitung",
        gerente_login_desc: "Geben Sie den Management-Audit-Schlüssel ein",
        gerente_placeholder_clave: "Zugriffsschlüssel...",
        gerente_btn_ingresar: "Panel betreten",
        gerente_titulo_principal: "Autohaus - Audit-Kontrolle",
        btn_salir: "Abmelden",
        gerente_kpi_total: "Gesamte Leads",
        gerente_kpi_verde: "Jetzt Fortfahren (Grün)",
        gerente_kpi_amarillo: "In Bearbeitung (Gelb)",
        gerente_kpi_rojo: "Auf Bedingungen Warten (Rot)",
        gerente_seccion_estatus: "Kundenreifungsstatus",
        gerente_html_title: "Management-Panel - Agentur-Lead-Steuerung",
        gerente_login_titulo: "Handelsleitung",
        gerente_login_desc: "Geben Sie den Management-Audit-Schlüssel ein",
        gerente_placeholder_clave: "Zugriffsschlüssel...",
        gerente_btn_ingresar: "Panel betreten",
        gerente_titulo_principal: "Autohaus - Audit-Kontrolle",
        btn_salir: "Abmelden",
        gerente_kpi_total: "Gesamte Leads",
        gerente_kpi_verde: "Jetzt Fortfahren (Grün)",
        gerente_kpi_amarillo: "In Bearbeitung (Gelb)",
        gerente_kpi_rojo: "Auf Bedingungen Warten (Rot)",
        gerente_seccion_estatus: "Kundenreifungsstatus",
        gerente_btn_excel: "Excel Herunterladen (CSV)",
        gerente_btn_limpiar: "Panel Leeren",
        gerente_th_estado: "STATUS",
        gerente_th_cliente: "KUNDE / INTERESSENT",
        gerente_th_contacto: "TELEFON / KONTAKT",
        gerente_th_asesor: "ZUGEWIESENER BERATER",
        gerente_th_fecha: "ERSTER KONTAKT / DATUM",
        gerente_th_intentos: "NACHVERFOLGUNGSVERSUCHE",
        gerente_html_title: "Management-Panel - Agentur-Lead-Steuerung",
        gerente_login_titulo: "Handelsleitung",
        gerente_login_desc: "Geben Sie den Management-Audit-Schlüssel ein",
        gerente_placeholder_clave: "Zugriffsschlüssel...",
        gerente_btn_ingresar: "Panel betreten",
        gerente_titulo_principal: "Autohaus - Audit-Kontrolle",
        btn_salir: "Abmelden",
        gerente_kpi_total: "Gesamte Leads",
        gerente_kpi_verde: "Jetzt Fortfahren (Grün)",
        gerente_kpi_amarillo: "In Bearbeitung (Gelb)",
        gerente_kpi_rojo: "Auf Bedingungen Warten (Rot)",
        gerente_seccion_estatus: "Kundenreifungsstatus",
        gerente_btn_excel: "Excel Herunterladen (CSV)",
        gerente_btn_limpiar: "Panel Leeren",
        gerente_th_estado: "STATUS",
        gerente_th_cliente: "KUNDE / INTERESSENT",
        gerente_th_contacto: "TELEFON / KONTAKT",
        gerente_th_asesor: "ZUGEWIESENER BERATER",
        gerente_th_fecha: "ERSTER KONTAKT / DATUM",
        gerente_th_intentos: "NACHVERFOLGUNGSVERSUCHE",
        gerente_seccion_record: "Link-Versand-Rekord nach Berater",
        gerente_th_asesor_nombre: "BERATER",
        gerente_th_total_envios: "GESAMTE SENDUNGEN / TEILUNGEN",
        gerente_seccion_reseñas: "Vertrauliche Bewertungen und Beraterrezensionen",
        gerente_th_fecha_res: "DATUM",
        gerente_th_asesor_eval: "BEURTEILTER BERATER",
        gerente_th_calificacion: "BEWERTUNG",
        gerente_th_comentario: "KUNDENKOMMENTAR",
        alerta_calificacion_exito: "Bewertung erfolgreich für das Management-Panel gespeichert!",
    alerta_vaciar_panel: "Sind Sie sicher, dass Sie das Audit-Panel vollständig leeren möchten?",
    alerta_excel_vacio: "Keine Lead-Datensätze zum Exportieren.",
    gerente_texto_envios: "Sendungen",
    gerente_texto_veces: "Mal",
    status_green: "Mit dem Verkauf fortfahren",
    status_yellow: "Nachverfolgung und Warnung",
    status_red: "Vollstopp / Untersuchung",
    cat_btn_main: "MODELL- UND DIENSTLEISTUNGSKATALOG", 
        cat_modal_title: "HANDELSKATALOG", 
        cat_modal_subtitle: "Wählen Sie den Bereich Ihres Interesses", 
        cat_btn_autos: "FAHRZEUGKATALOG", 
        cat_btn_servicios: "MASSGESCHNEIDERTE DIENSTLEISTUNGEN",
        cat_btn_interes: "Das interessiert mich",
        cat_btn_comentar: "Kontaktieren Sie uns",
        cat_desc_serv: "Persönliche und fachkundige Betreuung.",
        cat_btn_main: "MODELL- UND DIENSTLEISTUNGSKATALOG", 
        cat_modal_title: "HANDELSKATALOG", 
        cat_modal_subtitle: "Wählen Sie den Bereich Ihres Interesses", 
        cat_btn_autos: "FAHRZEUGKATALOG", 
        cat_btn_servicios: "MASSGESCHNEIDERTE DIENSTLEISTUNGEN",
        cat_btn_interes: "Das interessiert mich",
        cat_btn_comentar: "Kontaktieren Sie uns",
        cat_desc_serv: "Persönliche und fachkundige Betreuung."
    },
    zh: {
        titulo_app: "SIPVEC - 商业智能系统",
        bienvenida: "欢迎",
        menu_quienes: "关于我们",
        menu_excelencia: "卓越",
        menu_asistente: "快速助手与常见问题",
        menu_redes: "WhatsApp 与 社交媒体",
        btn_evolucion: "视频 / 与我们一起体验演变",
        btn_asesor: "选择您的专业顾问 / 地图！",
        btn_cuestionario: "开始问卷",
        btn_valoracion: "评价您的顾问服务",
        btn_finalizar: "完成并提交",
        btn_compartir_experiencia: "我在 ZENITH CAR 进行了购买。非常棒的体验！分享给你。",
        footer_producido: "由 \"PIDE YA\" CARD 制作",
        modal_evolucion_titulo: "体验演变",
        modal_evolucion_subtitulo: "发现我们的独特之处",
        btn_lujo: "您应得的奢华",
        btn_tecnologia: "技术与创新",
        btn_momento: "这是您的时刻",
        btn_asistencia: "专业协助",
        faq_titulo: "常见问题",
        faq_q1: "购买或租赁车辆包含什么？",
        faq_r1: "我们所有的车辆都包含原厂保修、免费满箱油、道路安全套件以及交付前的严格精洗细节处理。",
        faq_q2: "设施或交付点在哪里？",
        faq_r2: "我们的主要展厅和交付区位于主展厅。预约时将通过 WhatsApp 发送详细说明。",
        faq_q3: "取消或定金退款政策是什么？",
        faq_r3: "如果取消信贷流程或在签订合同前至少 48 小时申请取消，则全额退款。",
        faq_q4: "我如何预定或贷款买车？",
        faq_r4: "您可以通过银行卡或转账支付首付来锁定车辆，并在交车时结清尾款或启动分期付款计划。",
        faq_q5: "你们提供试驾（Test Drive）选项吗？",
        faq_r5: "当然！我们为所有现售车型提供试驾服务，只需提前预约并出示有效驾照即可。",
        contact_titulo: "联系我们",
        contact_sub: "请关注我们的官方网络和频道！",
        btn_wsp: "WhatsApp 聊天",
        btn_web: "官方网站",
        btn_fb: "官方 Facebook",
        btn_ig: "Instagram",
        qr_titulo: "扫描二维码",
        btn_qr: "分享二维码",
        cat1_t: "关于我们",
        cat1_c: "ZENITH CAR 重新定义了该地区的豪华移动出行，提供高工程车辆、纯粹的运动性能、尖端安全性和精致设计，将日常驾驶体验提升为真正的驾驶乐趣。",
        cat2_t: "卓越",
        cat2_c: "探索我们的高端汽车服务系列：ZENITH CAR 系列新车销售、量身定制的企业及个人金融方案、个性化试驾体验、高度专业化的机械车间以及原厂配件销售。",
        cat3_t: "满意客户",
        cat3_c: "我们的首要任务是卓越的服务。阿瓜斯卡连特스의车主和家庭一致认可 ZENITH CAR 的先进工程和运动精神所带来的品质、舒适感和卓越性能。",
        header_asistente_titulo: "个性化助手",
        header_asistente_bienvenida: "欢迎！让我们帮助您找到最适合您的专家。只需几秒钟回答几个简短的问题。",
        paso1_titulo: "第一步：潜在客户基本信息",
        paso1_desc: "这些数据有助于及时跟进。",
        label_nombre: "全名 *",
        label_whatsapp: "WhatsApp *",
        label_correo: "电子邮件（可选）",
        label_contacto: "您倾向于哪种联系方式？",
        btn_wsp_contacto: "WhatsApp",
        btn_llamada: "通话",
        btn_correo_contacto: "电子邮件",
        btn_regresar: "返回菜单",
        resena_titulo: "服务评估（机密）",
        resena_desc: "请选择您的顾问，以便将您的评分直接发送给销售管理部门。",
        paso2_titulo: "第二步：您对哪款车型感兴趣？",
        paso2_desc: "告知顾问哪些车型在市场上最受欢迎。",
        btn_modelo_sedan: "轿车 / 紧凑型车",
        btn_modelo_suv: "SUV / 越野车",
        btn_modelo_deportivo: "跑车 / 高性能",
        btn_modelo_pickup: "皮卡",
        btn_modelo_hibrido: "混动 / 电动车",
        btn_modelo_nose: "还没决定",
        paso3_titulo: "第三步：您在寻找哪种类型的车辆？",
        paso3_desc: "汽车轮廓的初步剖析。",
        btn_tipo_suv: "SUV",
        btn_tipo_sedan: "轿车",
        btn_tipo_deportivo: "跑车",
        btn_tipo_electrico: "电动车",
        btn_tipo_hibrido: "混动车",
        btn_tipo_familiar: "家用车",
        btn_tipo_ejecutivo: "行政车",
        btn_tipo_otro: "其他",
        paso4_titulo: "第四步：您主要将其用于什么用途？",
        paso4_desc: "商业技术效用细分。",
        btn_uso_personal: "个人使用",
        btn_uso_familiar: "家庭使用",
        btn_uso_empresa: "企业",
        btn_uso_uber: "Uber / 滴滴专车",
        btn_uso_viajes: "旅行",
        btn_uso_trabajo: "工作",
        btn_uso_otro: "其他",
        paso5_titulo: "第五步：您计划什么时候购买？",
        paso5_desc: "这一紧迫性指标对管理层至关重要。",
        btn_tiempo_semana: "本周",
        btn_tiempo_mes: "本月",
        btn_tiempo_3meses: "3个月内",
        btn_tiempo_6meses: "6个月内",
        btn_tiempo_investigando: "仅在了解中",
        btn_anterior: "上一页",
        btn_siguiente: "下一页",
        paso6_titulo: "第六步：您计划如何购买？",
        paso6_desc: "财务方案分析。",
        btn_metodo_contado: "全款购买",
        btn_metodo_credito: "信贷（贷款）",
        btn_metodo_arrendamiento: "租赁",
        btn_metodo_nose: "还没决定",
        paso7_titulo: "第七步：您的大致预算是多少？",
        paso7_desc: "购买力分类。",
        paso8_titulo: "第八步：哪项促销活动最吸引您的注意？",
        paso8_desc: "直接衡量当前活动的效果。",
        btn_promo_verano: "夏季奖金",
        btn_promo_tasa: "8.99% 利率",
        btn_promo_seguro: "免费保险",
        btn_promo_mantenimiento: "包含保养",
        btn_promo_test: "试驾 (Test Drive)",
        btn_promo_otro: "其他",
        paso9_titulo: "第九步：您是如何了解我们的代理机构的？",
        paso9_desc: "广告投资回报率 (ROI) 的纯审计。",
        btn_origen_asesor: "我的顾问",
        btn_origen_amigo: "朋友推荐",
        btn_origen_fb: "Facebook",
        btn_origen_ig: "Instagram",
        btn_origen_wa: "WhatsApp",
        btn_origen_google: "Google",
        btn_origen_web: "网站",
        btn_origen_qr: "二维码",
        btn_origen_otro: "其他",
        paso10_titulo: "第十步：建议顾问",
        paso10_desc: "根据您提供的信息，我们建议该顾问。请点击其标签：",
        paso10_cambiar: "如果您愿意，可以在此处更改：",
        btn_finalizar: "完成并发送",
        titulo_asesor_digital: "联系您的数字顾问",
        desc_asesor_digital: "选择您偏好的顾问以获取即时协助 / 点击其姓名。",
        btn_como_llegar: "如何到达",
        btn_cerrar: "关闭",
        footer_producido: "制作:",
        gerente_titulo_principal: "汽车经销商 - 审计控制",
        btn_salir: "退出",
        gerente_html_title: "管理面板 - 代理商潜在客户控制",
        gerente_login_titulo: "商业总监",
        gerente_login_desc: "请输入管理审核密匙",
        gerente_placeholder_clave: "访问密钥...",
        gerente_btn_ingresar: "进入面板",
        gerente_titulo_principal: "汽车经销店 - 审计控制",
        btn_salir: "退出",
        gerente_html_title: "管理面板 - 代理商潜在客户控制",
        gerente_login_titulo: "商业总监",
        gerente_login_desc: "请输入管理审核密匙",
        gerente_placeholder_clave: "访问密钥...",
        gerente_btn_ingresar: "进入面板",
        gerente_titulo_principal: "汽车经销店 - 审计控制",
        btn_salir: "退出",
        gerente_kpi_total: "潜在客户总数",
        gerente_kpi_verde: "立即推进 (绿色)",
        gerente_kpi_amarillo: "跟进中 (黄色)",
        gerente_kpi_rojo: "等待条件 (红色)",
        gerente_seccion_estatus: "客户成熟度状态",
        gerente_html_title: "管理面板 - 代理商潜在客户控制",
        gerente_login_titulo: "商业总监",
        gerente_login_desc: "请输入管理审核密匙",
        gerente_placeholder_clave: "访问密钥...",
        gerente_btn_ingresar: "进入面板",
        gerente_titulo_principal: "汽车经销店 - 审计控制",
        btn_salir: "退出",
        gerente_kpi_total: "潜在客户总数",
        gerente_kpi_verde: "立即推进 (绿色)",
        gerente_kpi_amarillo: "跟进中 (黄色)",
        gerente_kpi_rojo: "等待条件 (红色)",
        gerente_seccion_estatus: "客户成熟度状态",
        gerente_btn_excel: "下载 Excel (CSV)",
        gerente_btn_limpiar: "清除面板",
        gerente_th_estado: "状态",
        gerente_th_cliente: "客户 / 潜在客户",
        gerente_th_contacto: "电话 / 联系方式",
        gerente_th_asesor: "指派顾问",
        gerente_th_fecha: "首次联系 / 日期",
        gerente_th_intentos: "跟进尝试次数",
        gerente_html_title: "管理面板 - 代理商潜在客户控制",
        gerente_login_titulo: "商业总监",
        gerente_login_desc: "请输入管理审核密匙",
        gerente_placeholder_clave: "访问密钥...",
        gerente_btn_ingresar: "进入面板",
        gerente_titulo_principal: "汽车经销店 - 审计控制",
        btn_salir: "退出",
        gerente_kpi_total: "潜在客户总数",
        gerente_kpi_verde: "立即推进 (绿色)",
        gerente_kpi_amarillo: "跟进中 (黄色)",
        gerente_kpi_rojo: "等待条件 (红色)",
        gerente_seccion_estatus: "客户成熟度状态",
        gerente_btn_excel: "下载 Excel (CSV)",
        gerente_btn_limpiar: "清除面板",
        gerente_th_estado: "状态",
        gerente_th_cliente: "客户 / 潜在客户",
        gerente_th_contacto: "电话 / 联系方式",
        gerente_th_asesor: "指派顾问",
        gerente_th_fecha: "首次联系 / 日期",
        gerente_th_intentos: "跟进尝试次数",
        gerente_seccion_record: "各顾问链接发送记录",
        gerente_th_asesor_nombre: "顾问",
        gerente_th_total_envios: "发送 / 分享总数",
        gerente_seccion_reseñas: "机密评估与顾问评价",
        gerente_th_fecha_res: "日期",
        gerente_th_asesor_eval: "被评估顾问",
        gerente_th_calificacion: "评分",
        gerente_th_comentario: "客户评论",
        alerta_calificacion_exito: "评分区已成功保存到管理面板！",
    alerta_vaciar_panel: "您确定要完全清空审核面板吗？",
    alerta_excel_vacio: "没有可导出的潜在客户记录。",
    gerente_texto_envios: "发送",
    gerente_texto_veces: "次",
    status_green: "继续销售",
    status_yellow: "跟进和提醒",
    status_red: "全面停止 / 调查中",
    cat_btn_main: "型号和服务目录", 
        cat_modal_title: "商业目录", 
        cat_modal_subtitle: "选择您感兴趣的部分", 
        cat_btn_autos: "汽车目录", 
        cat_btn_servicios: "定制服务",
        cat_btn_interes: "我感兴趣",
        cat_btn_comentar: "联系我们",
        cat_desc_serv: "个性化专业服务。",
        cat_btn_main: "型号和服务目录", 
        cat_modal_title: "商业目录", 
        cat_modal_subtitle: "选择您感兴趣的部分", 
        cat_btn_autos: "汽车目录", 
        cat_btn_servicios: "定制服务",
        cat_btn_interes: "我感兴趣",
        cat_btn_comentar: "联系我们",
        cat_desc_serv: "个性化专业服务。"
    }
};

function cambiarIdioma(lang) {
    if (!DICTIONARY[lang]) return;
    
    // Guardar preferencia
    localStorage.setItem('sipv_lang', lang);
    
    // Actualizar elementos data-i18n
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (DICTIONARY[lang][key]) {
            el.innerText = DICTIONARY[lang][key];
        }
    });

    // Sincroniza configuraciones externas si existen
    if (typeof CONFIG !== 'undefined' && CONFIG.textos) {
        ['cat1', 'cat2', 'cat3'].forEach(cat => {
            if (DICTIONARY[lang][cat + '_t']) CONFIG.textos[cat].t = DICTIONARY[lang][cat + '_t'];
            if (DICTIONARY[lang][cat + '_c']) CONFIG.textos[cat].c = DICTIONARY[lang][cat + '_c'];
        });
    }
}

document.addEventListener("DOMContentLoaded", () => {
    const langGuardado = localStorage.getItem('sipv_lang') || 'es';
    cambiarIdioma(langGuardado);
    
    const selector = document.getElementById('cambiador-idioma');
    if (selector) {
        selector.value = langGuardado;
        selector.addEventListener('change', (e) => cambiarIdioma(e.target.value));
    }
});